== Introduction.

Our late worthy friend William Reckitt, whose journal follows,
was one whom the Lord was pleased to prepare for his service;
and having in a good degree experienced the work of righteousness to be peace,
he was engaged, under the influence of divine love, to call others to come,
taste and see that the Lord is good.

His life and conversation were innocent and consistent with his profession,
and in the exercise of his ministry,
he was attended with that love which seeks the good of all.

As the following journal commences only with his voyage to America,
a short account of him, of the work on his mind,
and of his services before he embarked for America, seems not improper.

He was born at Lea, near Gainsborough, in Lincolnshire, about the year 1706,
of parents professing truth; his mother died when he was young,
and his father being through infirmities rendered incapable of supporting his children,
he was bound by friends, at nine years of age until he arrived at twenty-one,
as an apprentice to a weaver; which proved a laborious servitude,
his master being in low circumstances.
In the course of his service his master let him out to harvest work,
in which employment his industry gained him the confidence
of the farmer that employed him,
who thought it unnecessary to look after him, saying William was a faithful servant;
as he was to his master to the end of his apprenticeship.
During which time he was reached by a divine visitation,
through the ministry of a friend on a religious visit, whose testimony,
as he has been heard to relate, clearly answered the witness of truth in his own heart,
and fully confirmed him that the principles of friends
were consonant with the holy Scriptures;
and he then thought there would be none so void of understanding as not to be
convinced by the same powerful declaration of the true Christian faith.
It left a lasting impression on his mind;
an hunger and thirst after righteousness were begotten in his soul;
and by a diligent attention to the dictates thereof,
he experienced preservation from the many temptations,
to which unguarded youth are exposed.
About the eighteenth year of his age, the death of an only sister,
a virtuous young woman, who had been particularly kind to him, nearly affected him;
and an only brother, by giving way to the vanities of the world, was drawn aside,
and left the Society.
These events impressed his mind with deep sorrow and humiliation;
but feeling the preserving hand of divine goodness manifested for his support,
he was engaged to live near thereto, by which he was mercifully preserved.

Soon after the expiration of his apprenticeship,
he removed into the compass of Wainsfleet monthly meeting in Lincolnshire,
where he followed the business of a weaver, and increased in the esteem of his friends;
being a man who laboured to be in reality what he professed.
In the year 1731, he entered into the marriage state with Ellen Maw,
a sober and virtuous young woman, who was an affectionate wife to him,
and tender mother to their children; he survived her,
she dying during his absence on his second visit to America.

About the thirty-sixth year of his age,
he first appeared in the ministry to the satisfaction of friends,
and laboured diligently in his own and some neighbouring
meetings for the advancement of truth;
and after some time, in company with Robert Kinsley, he visited the churches in Essex;
and about the latter end of 1745, in company with the same friend,
also visited the city of London;
and his service in this visit is still remembered
by some with brotherly regard and affection.

In 1746 he visited the west of England, and part of Wales; and in 1752,
in company with Samuel Stott, of Edmondsbury, he visited Ireland,
to his own and friends`' comfort and satisfaction, and returned home with peace of mind.
In 1756 he visited Yorkshire; soon after which, in the course of his religious labours,
he found himself engaged to visit the churches in the American plantations,
the ensuing account whereof will best inform the reader of his progress therein.

It is not intended to magnify the creature by any thing
which may be said concerning this our deceased friend;
but to show the reader that such as believe in,
and live near to the divine principle of truth in their own hearts,
convey an evidence of it to the minds of those who behold them;
for he being taken in his passage by a privateer, England being then at war with France,
and carried into Morlaix, was there detained in a painful state of captivity,
yet was preserved in great quietness and resignation,
to the admiration of some of the French inhabitants; one of whom,
in a letter to a person residing in London, mentioned his inoffensive,
lamb-like behaviour in terms of great respect, and when he was removed to Carhaix,
recommended him to a person of account, a member of the parliament of Brittany,
who likewise testified his regard to him.
The kindness he received from these persons moderated his captivity,
though he had many exercises there, which often brought him very low;
yet he found support and preservation, as he acknowledged in his letters,
in one of which, after having noted how he had been helped,
and expressing his care for his future preservation, he says;
"`My fears have all been concerning myself,
for surely I never saw more of my own weakness;
it hath indeed been a searching time to me; and yet it springs in my heart to say,
if the Lord hath any delight in me, he will bring me safe through all.
He knows the integrity of my heart.
I did not set out in a forward spirit, but in his counsel,
and in it at this time I stand; he knows best what will be most for his own honour.
And as to what will become of this earthly tabernacle,
it seems to be the least of my care, so that I may finish my course with joy.`"

After being detained about five months,
he was released through the kindness of a person in England, who,
having received very favourable impressions of him
through the French merchant before mentioned,
recommended him to the secretary of the sick and wounded office,
they having the care of such as were prisoners, and after a short stay at home,
finding the engagement remain, he returned to London, attended the yearly meeting,
and with the concurrence of friends, proceeded on his voyage,
of which the following is his own relation.
