== Supplement.

In the course of these travels the author often had his wife and children in his remembrance,
and wrote to them,
to encourage them to trust in that hand which had drawn him into service.

By a note, dated the 8th of the eighth month 1768, on one of his letters,
he desires that they might be preserved for the sake of his children: "`When,`" says he,
"`my head is laid in the silent grave, and my soul at rest with the Lord;
and also that my Journal may be transcribed for their perusal;`" adding,
that the very fragments should be "`gathered up, that nothing may be lost.`"
For the benefit of his surviving relations, and of mankind in general,
the following extracts are inserted.
They show the care he had for their welfare, when far absent,
and bespeak the fervency of his love.
The first was from France, while he was a prisoner there, and is as follows.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Carhaix, in France, the 23rd of the Twelfth month, 1756.

[.salutation]
Dear wife and children,

This comes to inform you of my welfare, and though outwardly confined,
not having liberty to proceed on my journey at present, yet I dare not complain, nor say,
the Lord is an hard master; for in his great mercy and matchless lovingkindness,
he hath been a present help in every needful time,
as mine eye hath been single to him--he hath supported me under
the exceeding great exercises I have already met with in this journey.
Glory and honour be to his great Name forever!

I would that none of you might be cast down about me,
but still trust in the name of the Lord.
I am fully satisfied you will find it to be a strong tower,
and as the shadow of a mighty rock in a weary land.
And there is one thing I do greatly desire of you, that is,
live in true love and unity one with another, and, as much as in you lies,
with all men everywhere,
and then the God of love and peace will be with you to the end of your time.
I wrote about the seventh or eighth of last month, in which I informed you how I fared,
and was in health; since which I am removed to this place, a tolerable situation,
and provisions pretty cheap.
I have a chamber to myself, and a good bed, being under no restraint,
but have the liberty of the town and fields to walk in when I please.
I hope to receive a letter from you in a little time.
I most dearly and tenderly salute you, and bid you farewell.

[.signed-section-signature]
William Reckitt.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, the 29th of the Fifth month, 1758.

[.salutation]
Dear wife and children,

I came here this day,
having been something more than six months in the southern provinces; in which visit,
though the journey has been attended with some difficulties and dangers,
yet I have no cause to complain.
I lacked for nothing, it having at times been made easy,
pleasant and comfortable to me in Christ, for whose sake and the Gospel`'s,
I have endeavoured to be given up,
according to the dispensation of his grace given to me, in obedience to his will,
in which I desire I may stand faithful to the end.
The same desire at times, is strong in my heart for all of you that I have left behind,
that you may be faithful to the measure and manifestation of grace given unto you.
I am not without fear, lest some of my dear children,
who are grown to years of understanding, should through unwatchfulness and carelessness,
be drawn away into hurtful things.
It drops as a watch word for you to take notice of, which, if you do,
and walk agreeably unto the blessed principle of truth, which you have heard,
and I trust, believed in, the Lord hath blessings in store for you,
which will make you truly rich, and add no sorrow with it.
I should have no greater comfort at my return,
than to see it was your care and chiefest concern to be faithful to the Lord,
according to the best of your understandings.
This would be more to my comfort and solid satisfaction,
than for you to have abundance of this world;
for they that first seek the kingdom of God and his righteousness, the promise is,
that all other things shall be added.
I often breathe to the Lord, that he, above all things,
may be pleased to sanctify and cleanse your hearts from all sin,
that so he who hath hitherto been the help, strength,
preservation and deliverance of your poor father in his exercises and troubles,
may in mercy bless you all, and take delight in you, so as to tender your hearts,
and favour you often with his power and living presence, is the sincere prayer of yours,
in that love that neither distance nor length of time can separate.

[.signed-section-signature]
William Reckitt.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Newport, in Rhode Island, the 5th of the Eleventh month, 1758.

[.salutation]
My dear wife,

These may inform thee and the children,
that I have hitherto been favoured in a good degree of health
and strength to go through the exercises and travels,
both inward and outward, which have laid before me, for the sake of the gospel;
in the discharge whereof, at times, I find great peace and inward consolation.

My time of stay in this land, at present, seems uncertain;
yet I am ready to conclude it will be until another year; if sooner,
I believe it will be acceptable both to you and me:
if we be willing to wait in patience the Lord`'s time he will be well pleased with us,
and undoubtedly his blessing will follow, which will make truly rich,
and add no sorrow with it.

I have received two letters from you, in which I had an account of your welfare,
in a good degree,
for which I am truly thankful to Him that hath hitherto helped us and preserved us.
May he have the praise, who is worthy!
His ways are all ways of pleasantness, and his paths are indeed paths of true peace,
and his mercies and lovingkindness are towards all
them that daily live and dwell in his holy fear.

May all my children learn the fear of the Lord,
is often my earnest cry and prayer to the Lord for them.
Then would they be preserved out of the evils that are in the world, for they are many,
and lie close to their youthful inclinations, and if they give way to them,
will draw their hearts from the Lord, and out of his holy fear into a loose, wanton,
and libertine spirit, which I caution and warn them to watch against and beware of,
lest they lose the blessing, as Esau did,
and the time come they may carefully seek it with tears, and cannot obtain it.
Time is very precious, and ought to be prized by all.
Some very young in years, when on a dying bed, have bemoaned themselves,
and lamented their misspent time, the sense of which causes me almost to tremble,
lest it should be the state of any that see or hear these lines read.
Therefore I entreat there may be a turning to the Lord with the whole heart;
and make no reserves or excuses, but yield obedience to his holy will in all things,
according to the best of your understandings,
though through a great cross to your inclinations.
It is the way to obtain mercy with God,
and admittance into his everlasting kingdom of rest and peace,
when time in this world of troubles shall terminate.

I dearly salute thee and our children in the love of the Father of all our mercies,
desiring you may all dwell in his love, that so you may feel me to be near you in spirit,
though outwardly far separated.
The dead cannot praise the Lord, but the living; the sense of it at this time,
for his unspeakable favours to us, with many more of his dear children,
whom he hath begotten into a lively hope, bows my spirit.
May we all be preserved under a living sense of this life,
that when under a degree of divine favour, we may be enabled to draw near to Him,
who knows all our wants, and put up our prayers and supplications for each other,
in a manner that will find acceptance,
is the pathetic breathing of thine in that love that changeth not,
including our dear children.

[.signed-section-signature]
William Reckitt.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, the 12th of the First month, 1759.

[.salutation]
Dear love,

I have received several letters from home,
which intimate thine and our children`'s welfare, as to health,
which gives me great satisfaction, with desires, if it be the will of divine Providence,
such blessings may be continued, and we truly thankful.

I returned yesterday from New England and the eastern country,
having been somewhat more than five months in that journey.
Health of body is in a good degree still continued, and true peace of mind;
for which I am made, at times, to bless that great and everlasting Name, who is over all,
worthy forever!
I see I cannot enlarge,
only recommend thee to that which hath hitherto kept and preserved, and still will,
I am sensible, as we put our trust and dependence upon it.
I desire neither thou, nor any of you, will think me long.
I shall, as soon as I am clear, hasten home; shall not conclude for myself,
for I am not at my own disposal;
yet seem to think I shall look homeward in a little time.
My dear love to thee and the children, sympathizing with you in great nearness,
I dearly salute thee and them, in that which never changeth.
Thine in the Lord.

[.signed-section-signature]
William Reckitt.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, the 15th of the Sixth month, 1759.

[.salutation]
My dear wife and children,

I am in the perfect enjoyment of health, except some pain in my breast,
which is now much better.
It hath been a long time since I had a letter from England,
but here have been but few ships from London this summer.
I cannot conclude of fixing my return,
I having had drawings in my mind to visit Barbados,
and purpose taking the first suitable opportunity to embark for that place.
There are only a few meetings in Barbados, so that my stay is not likely to be long,
except I have to visit any other islands.
I may thus conclude at present,
but leave it to that great and good Disposer of all things, that hath been my support.
I may with gratitude and thankfulness say,
he hath been my present helper in every needful time.
Oh! may our eye be single to Him; he is good indeed unto all that put their trust in Him;
though great storms may rise, and clouds of thick darkness may appear,
I am strong in the faith, the Lord still will be on our side,
as we are concerned to be faithful unto him; and if he be on our side,
who can be against us?
I cannot enlarge much,
but desire that you and I may be enabled to commit ourselves to his care and protection;
for assuredly, a sparrow cannot fall to the ground without his permission,
and if we be faithful to him, we are of more value than many sparrows; for, saith he,
the hairs of your head are all numbered.
My earnest cries and supplications have often been for your souls`' welfare.
I would not have any of you think too much about me,
though I trust we love one another by the nearest bonds and ties of nature;
yet when the love of Truth prevails, we should give up one another for the sake thereof;
then in this world shall we be entitled to the hundred fold, which is true peace,
and in that which is to come life everlasting.
As a most affectionate husband and tender father, I dearly salute you,
and bid you farewell.

[.signed-section-signature]
William Reckitt.

[.postscript]
====

P+++.+++ S. I desire my children would not give way to
accompany themselves with those that are not friends,
for that hath been the ruin of many of our youth.
Endeavour, at all times, to attend religious meetings,
and also to learn and improve in reading and writing.
I am afraid lest you should not do well;
then I shall be grieved and sorrowful if I should live to see you again,
instead of being comforted and rejoicing in you.

====

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Christopher`'s, the 9th of the Tenth month, 1759.

[.salutation]
Dear wife and children,

These are to inform you, and all inquiring friends and relations,
that I have great and good satisfaction since I arrived at this part of the world,
in the discharge of what I have thought to be my duty,
notwithstanding I have been exposed to some hardships,
and have likewise been out of health about four weeks, but am now as well as usual,
can travel, and have a good appetite.
Yesterday I came from an island called Nevis, where I have had several meetings;
and though I have thoughts of visiting another island or two, I shall not, I trust,
stay long in these parts, except I am detained longer than I expect.

I have you all nearly and dearly in my remembrance,
though I have been already longer from you, or am likely to be longer than I expected;
yet I trust we shall find it hath all been the Lord`'s doing,
and as we patiently wait on him, shall find his ways to be ways of pleasantness,
and his paths to be paths of true peace and joy in the Holy Ghost,
and that his time is always the best time.
I would that none might be too anxious and thoughtful concerning me,
seeing the same hand that drew me forth is as able, if he sees meet, to return with me,
and bring again to you in safety; and if not, let us not murmur or repine,
if it may but be with us as it was with the apostle, who said, "`To me to live is Christ,
but to die is gain.`"
I cannot write much for want of time; the ship is near sailing, as I am informed,
but commend you to the Lord, as into the hand of a merciful Creator and tender Father,
tender in mercy to all that faithfully serve, worship and obey him.

[.signed-section-closing]
My spirit salutes thee and dear children, etc.

[.signed-section-signature]
William Reckitt.

--

Our friend having left no further account of his travels after this voyage,
until his second embarkation for America,
there is reason to suppose he travelled but little,
except attending the yearly meeting in London, or some short distances near home.
But about the year 1764, he again found a concern to visit friends in America.
For this purpose he embarked in company with Thomas Goodwin and William Home,
who were returning home from a religious visit to this nation,
and arrived safe at Philadelphia, and proceeded through most of the provinces;
but his wife dying during his absence, he, on account of his family,
rather hastened his return, and embarked in a vessel bound for Ireland;
from whence he came to London about the fourth month, 1766,
and soon after returned to Wainfleet, the place of his residence.

Of this voyage, he kept only minutes of the meetings he visited;
so that we are deprived of a particular account thereof.

After his return, he visited divers parts of this nation,
and in particular the city of London,
which he often hinted he thought might be the last time;
but his love to the cause of Truth continued,
and it was evident the fervency of his mind was as strong as ever.

He was a man of great integrity of heart, a lover of peace,
and sought the promotion thereof,
and had often a word of counsel to drop tending to edification.
Not only at particular opportunities, but often, when absent,
has he imparted of the goodness and mercy of the Lord to his soul,
and also been helpful in counsel by letters.
In one of the last I had from him, he expressed himself thus:
"`The sap of life lies very deep in the root,
and that must be waited for in those pinching times I have met with;
and yet I have a comfortable hope raised in me of late, that all will be well in the end,
the prospect of which to me, hath seemed exceedingly pleasant, and, if safe,
should much desire it might be hastened; but that is not my proper business to look for,
or to desire the reward before the day`'s work is finished.
I have served a good master,
but have ever looked on myself as one of the weakest of his servants;
yet have endeavoured to come up in faithful obedience to his will made manifest in me,
and in this now I have great peace and an assurance
of an inheritance that will never fade away,
if I continue in the way of well-doing to the end of the race.`"

His illness was very short; he was taken with a fit of the ague at night,
and next morning, about four, departed this life, the 6th of the fourth month, 1769,
and was interred in friends`' burial-ground the 9th of the same, at Wainfleet,
aged about sixty-three years.

The long and intimate acquaintance I had with our deceased friend,
hath induced me to prepare these accounts for more general service,
in which I have had real satisfaction and comfort;
and if they afford the same to the reader, my end is answered.

[.signed-section-signature]
Thomas Wagstaffe

[.signed-section-context-close]
London, 29th of the Seventh month, 1776.
