[short="Testimony from Wainsfleet Monthly Meeting"]
== A Testimony from Our Monthly Meeting at Wainsfleet, in the County of Lincoln, Concerning Our Deceased Friend, William Reckitt.

This our worthy friend, was born in the year 1706,
within the compass of Gainsborough monthly meeting, of parents professing truth,
who died when he was young.
His friends put him apprentice to a weaver belonging to the same monthly meeting,
with whom we believe he served his time faithfully,
and then came to live near Partney Mills, within the compass of our monthly meeting.

After some time, about the year 1742,
it pleased the Lord to call him into the work of the ministry;
his appearance from the first was in the life and wisdom of truth,
which nearly united him to his friends.
Soon after he removed to Wainsfleet particular meeting;
and sometime after he visited friends in the west of England and Wales, etc.,
and at different times many other different counties; also Ireland once,
with our friend Samuel Stott.
He was twice in America; the first time he set forward in the year 1756,
and it being in the time of war, was taken prisoner into France,
and confined about six months,
which he bore with Christian fortitude--as some of us have heard him say--and
got well home to his family in the beginning of the year 1757,
where he stayed about four weeks, and then again set forward for his intended visit.
He afterwards found a weighty concern to visit his
friends in some parts of America again;
all which visits, by sundry accounts received, were much to friends satisfaction,
as well as his own; and indeed it may be truly said, he was deep in the ministry,
and powerful in prayer, his testimony sound and edifying,
which rendered him very near and valuable to many.
He was grave in conversation, yet innocently cheerful amongst his friends;
an affectionate husband and a tender parent.
We think it needless to enlarge concerning him, as he was well known to many friends;
only we may, with sincerity of heart, say his removal is much regretted in general.
In the latter end of 1768,
he had drawings in his mind to visit London and parts adjacent;
in which he told some of his near friends, he thought it might be the last time.

He returned home in the first month in the year 1769, but poorly in health,
and continued so, but mostly attended his own meeting,
where he had several weighty testimonies,
which had more than usual influence over the hearers,
leaving lasting impressions on their minds, as well as at times in private conversation,
wherein he signified he was willing to leave all these transitory and fading enjoyments,
whenever it might please the Lord to call him from works to rewards.

His illness was very short;
he was taken with a fit of the ague the day before his departure,
and next morning about four o`'clock, exchanged this life, we make no doubt,
for a better, the 6th of the fourth month, 1769, and was buried the 9th of same,
in friends`' burying ground at Wainsfieet, after a solemn meeting,
where a living testimony was borne to the truth, and to the satisfaction of many present.

Signed in and on behalf of the said meeting, held the 16th of the third month, 1770, by

[.signed-section-signature]
John Robbins, John Copeland, Thomas Reckitt, David Hopkins, Jonathan Nainby,
George Kitching, Pearson Smith, John Pearson, Joseph Burton, John Wright, Jr.

[.postscript]
====

The foregoing testimony concerning our dear friend William Reckitt, deceased,
was read and approved in our quarterly meeting held at Lincoln,
the 4th of the fourth month, 1770, and signed in and on behalf thereof, by

====

[.signed-section-signature]
John Massey, __Jr. Clerk.__
