[short="Chapter I"]
== Chapter I. Some Account of What Befell me in my First Voyage Towards America.

Having parted with several friends who accompanied me to Gravesend,
the 15th of the tenth month, 1756, I went on board the ship __Lydia,__ Joseph Riddell master.
We had three passengers besides myself, who seemed to be very sober men,
and carried themselves very lovingly to me, as likewise did all our common men;
though I often reproved them for swearing, and their bad language to one another.
The 20th we came into the Downs, but the wind not being fair, we lay there till the 22nd,
when the wind coming more favourable we weighed anchor.

It may not be amiss to mention the great exercise and weight
that rested upon my spirit while we lay here,
I then not seeing the cause of it.
When I looked forward, I could see little further than the Land`'s End,
and I cried in my mind that we might be carried or driven to Ireland;
for then I thought I should get safe to my journey`'s end;
but not seeing it would be so then, I only desired we might put into Plymouth,
which I mentioned to the captain, and he told me he thought he would.
But the wind coming fair, and a strong gale, he was willing to make the best of it.
We out-sailed two ships which came from the Downs with us,
one a privateer called the __St. Olive,__ from London; the other a Guineaman.
The 24th, about ten in the morning, we came abreast of Plymouth with a very fine wind.
In the evening, as I sat in the cabin,
something opened in my mind concerning my own preservation,
which I thought somewhat strange; but soon saw a cause for it.
For about eight o`'clock next morning,
the mate came down and told his master there was a French snow just astern of us,
which to our sorrow, was too true, for she was then within reach of us with her guns.
I thought it was a great neglect of our master and the sailors,
that they did not keep a strict look-out;
for they acknowledged if they had but had a few hours more,
they should not have been taken.
But then it was too late, they could not get their sails all properly bent,
as they would have done if due precaution had been taken.
The shot coming over us, I was afraid for our men.

During the little time we were chased,
the chief care our captain seemed to take was to save what he had,
so he kept pretty much in the cabin,
till his men called very earnestly for him to come upon deck.
Then he ordered them to strike,
and in a little time the Frenchman came and boarded us with great fury.
I was in the cabin, and stood still, some of them looking at me very sourly and fiercely,
but like so many hungry animals,
they fell to hunting and searching for what they could find,
till they dared not stay much longer.
One of them coming to me in a fawning manner, said, "`Sir,
I desire you would give me your money and watch, and I will give you them again.
I told him I had not much, and did not choose to part with it.
But he growing very earnest to have it,
I turned myself about and took three guineas out of my purse,
two of which I carried on shore, and gave him the remainder.
He looked at it and seemed not satisfied;
but the officers being in haste to get us all into the boat, I was had upon deck.
When I looked at the sea I thought it seemed as though I should not escape with my life;
therefore resolved to stay on board our vessel, if I might,
and went down again into the cabin;
but in a little time was fetched out and commanded to get into the boat.
The fear of death was then taken away,
and I was resolved to do the best I could to get in.
One of our sailors handed me a rope, but it was so short I was forced to let go,
not knowing whether I should fall into the sea or boat; for the sea ran very high,
and two of our men were lost during the short time I had been below.

They were getting into the boat when I was seized with fear,
and I saw it was not groundless; for had I then proceeded to get in,
I should in all probability have been drowned.
For as soon as I had turned my back to go down into the cabin,
the gunwale of the ship took the boat side, and had like to have sunk her,
and the two poor men were cast out.
The loss of them sorrowfully affected my mind; and the imminent danger I had been in,
with a sense of the Lord`'s goodness and mercy in preserving me at that time,
brought me very low, in humble thankfulness for so great a deliverance,
looking upon it as a mark of his tender care and
fatherly regard for so poor a creature as I am.

When we came up to the French ship, our men assisted me in getting on board,
and led me through a crowd of such creatures,
as I thought were more like brutes than men; but they offered me no violence.
When I came into the cabin I was placed behind a large chest of arms,
which was their table; where I sat for several hours very still,
and laboured to get to such a right and true composure of mind,
that I might be enabled to undergo with patience what had befallen me.

The hurry about the booty being pretty much over,
towards night they came to settle in the cabin;
and seeing me take little notice of what they either said or did,
they looked earnestly at me and asked our captain who I was.
He told them I was a Quaker minister and intended for Pennsylvania.
They made many fine speeches, and told me I was welcome to anything they had,
and would have me call for whatever I needed.
When food came to the table, they invited me to eat;
but I told them I was not for eating, my appetite being quite gone.
When they thought it was time for us to go to bed, I was had down into the hold,
which was so close, and the hammocks hung so near to one another,
I was forced to creep on my hands and knees till I came to that I was to lodge in.
The young man that conducted me was one of the officers,
and I understood he put me in his own hammock.

As he was making it fit, I thought he seemed to do it with a very good will;
but the place being strait, and I lying in all my clothes,
made it hard work for me to get in.
However, he stayed and helped me what he could, till I was settled in my new lodging.
A few hours after I had plenty of company.
As they crept under me they lifted me up,
and when they were all placed in their respective lodgings
I perceived some lay upon the boards under me.
However, the closeness of the place, and the disagreeable smell,
with a fear which then seized my mind, that these creatures would do me some mischief,
had like to have quite overset me, so that I was nigh fainting away,
and ready to query whether I should live till morning.
In this great strait the Lord appeared for my help.
I sensibly felt strength administered,
and it arose in my mind that those I was afraid of would not hurt me.
I believed it was the truth, and in a little time, being much wearied,
I fell into a sound sleep till morning.
When I came upon deck our poor men came to me and complained of their hard lodgings,
and what was worse, the thoughts of a close imprisonment when they should come on shore.
It made me sorrowful to hear their complaints,
for they had heard the prisoners fared very poorly.
I spoke as comfortably as I could, and exhorted them to live in the fear of the Lord.

This day we came up with a vessel bound for Plymouth,
taken from the French by one of the English ships of war.
The French soon brought her to, boarded her, and brought all the men to us but one.
The two officers were had into the cabin where we were.
The captain being a man of very strong passions,
to be taken prisoner was almost more than he could bear; when they were sat down,
I saw he was almost overcome with grief, which I a little wondered at.
After some time I went and sat by him, and said I would not have him too much cast down;
trouble and disappointment happened to all men,
and this was what such men as he might reasonably expect.
He said nothing as I remember, but soon went out,
and after a while came again with a Frenchman along with him, who could speak English,
and pretended great friendship to me,
and requested that I would go along with him and the captain into a private place,
for he was desirous to have some discourse with me.
It did not seem to suit my inclination, but through their much importuning me, I went.
When we were settled,
the Englishman told me he had been attended with misfortunes even from his childhood,
and thought he had been in a fair way of making his fortune,
but he had met with this disappointment, which was like to be a great loss to him.
He then began to talk about religion,
and expressed a great desire in his heart to live in the fear of the Lord.
He spoke highly of the ceremonies used among them, mentioning baptism with water,
and bread and wine, which they call the sacrament.
I told him we were not in the practice of using them,
believing such ceremonies not to be essential to salvation.
He said I was a strange man,
but finding myself not at all disposed to have any further discourse at that time,
I desired to withdraw.

I was much favoured with stillness, and a sweet composure of mind,
which to my great comfort,
I found did strengthen and fortify me against the assaults of the enemy,
which I met with both inwardly and outwardly.
When I looked at my present situation, and what was likely to be the consequence,
fearing I might be a stumbling block in the way of many, and bring dishonour to truth,
I was much cast down, and did often cry, "`Lord, if I had been worthy,
you would have preserved me out of the hands of such unreasonable men.`"
But the good Shepherd of Israel did cast his mantle of love over me,
and stilled my crying,
so that I was in a good degree made willing to submit to
what he should see fit to permit to come upon me.
While I was here,
fervent and strong desires were in my heart for those I had left behind me in many places,
that they might be preserved in the fear of the Lord.
As to outward food, I ate very little for several days.
Many said I should be sick, and often entreated me to eat;
but I did not eat much till I found I could take
it both with freedom of mind and a good appetite,
which had been quite gone.
The Frenchmen, as I frequently walked upon deck among them, were become milder,
and never offered to do me any harm, except one at the first,
and he was prevented from hurting me.
I also sat and walked often upon the quarter deck,
the officers all looking on me with a pleasant countenance, except the captain,
who I suppose, took offence at my not conforming to them when they went to prayers,
which was twice a day.

One evening, as we were sitting in the cabin,
a young Frenchman asked the man of war`'s captain before mentioned, pointing at me,
concerning our principles.
He told him we were a strange people; we both disowned baptism and the Lord`'s supper.
The Frenchman looked at me with disdain, and then began to speak much in behalf of both,
laying great stress especially upon the latter;
for he seemed a very zealous young man for their way.
Then both joining,
they came to a conclusion that those who were not
in the practice of them could not be saved.
Their discourse was in Latin, and though I am not a Latin scholar, I understood so much,
that I gathered the purport of their discourse.
When they had done,
I told the captain he had done very wrong in misrepresenting
the people called Quakers to that man.
He asked in what?
I told him I understood he had been telling him we disowned baptism and the supper.
He said he understood by me, that we did not own the sacraments.
I told him there was no such word made use of in Scripture that I knew of;
but baptism and the supper were,
and we owned and believed both to be essential to salvation.
My mind was then opened concerning baptism, in the several passages of Scripture,
which strengthen and confirm it,
that the baptism which is saving must needs be spiritual; and if so,
then no need of water; for the apostle says, "`One Lord, one faith,
one baptism;`" and that themselves owned water to be but
an outward and visible sign of an inward and spiritual grace.

I was led on till I came to that last supper or passover,
which our Lord did partake of with his disciples;
and told them what our Lord then said to his disciples, was, "`As often as you do this,
do it in remembrance of me, to show forth my death until I come.`"
This was no commandment to perpetuate that outward supper or passover;
that being a Jewish ordinance, which he then had nigh finished,
when he nailed the hand writing of ordinances to his cross.
But I told them they might see in the Revelations of John,
what he said concerning his coming, where he says, "`Behold,
I stand at the door and knock; and if any man hear my voice, and open the door,
I will come in to him, and sup with him, and he with me.`"
It is this supper and coming we own, and in our measure, partake of;
for this was the communion of the saints.
Several texts of Scripture opening in my mind to confirm that baptism and supper,
which are saving, to be spiritual; and as bodily exercise profits little,
so that which is only outward and elementary could not profit the soul.
They heard me very patiently, and did not make any objections.
Being pretty easy, I left them to have their discourse to themselves,
that the officer might have opportunity to inform the man what I had said.

Our confinement at sea was nearly over,
but as we came nigh in with the shore we were chased by an English man of war,
who came fast up with us, and gave our men great expectations of being released;
and indeed the Frenchmen expected no other than to be taken.
Every man prepared himself for removing, and was in great fear;
but we were so near the rocks, the man-of-war dared follow us no further,
only gave us one shot, which came over us, and then sheered off.
The great expectation our men were in of being retaken, was disappointed,
which made them more sorrowful than before; but it did not much affect me,
for I was now more reconciled in my mind to bear with patience
what the Lord should see fitting to try me with.
I had strongly desired before not to go to France,
but in a few hours we came into a small harbour with a fort at the entrance,
and in it one ship of war.
We did not land till next morning.
This night I met with something that was very unpleasant to me,
for the captain going on shore, and the men thinking all secure, when night came on,
most of them went to rest; but the man-of-war`'s captain and some of his men,
as it afterwards appeared, had consulted about cutting the vessel out of the harbour.
We had more liberty given this night than we had before.
The two man-of-war`'s-men, our captain and myself were ordered to lie in the cabin.
Riddell had lain in it before, but now he was to lie in the captain`'s hammock,
being a favourite, and I in his bed; but he not accepting of it, I got in.
This I perceived gave great offence, therefore, to prevent further trouble,
I soon quitted it, and sat me down by the man-of-war`'s captain, who had got to writing.

I had by this time contracted such an intimacy with him,
that I could make bold to see what he was writing, without giving him any offence;
and when I came to see what he was writing, and found it was only to spend time,
it gave me some uneasiness, for it then began to be late.
I did not suddenly say anything to him, but took notice of his motions and looks,
and saw his countenance was very much discomposed.
All began now to be very still.
None were up in the cabin but him and myself, and the young Frenchman before mentioned,
who kept guard, and he had no weapon in his hand.
I asked the captain if he was not for bed.
He said he could not go to bed.
I then told him I would not have him think of making
any attempts to take the vessel out of the harbour.
He said he should make no difficulty of it, if he had anybody to stand by him.
I signified that I thought it could not be done without much blood-shedding, if at all;
and I should be very sorry to see anything of that kind,
though my liberty was as dear to me as any of theirs was to them.
He said I need not be afraid; nobody would hurt me.
I told him that was more than he knew; for as I had been with them all the evening,
they would think I had a hand in the plot, and so I might lose my life undeservedly.

I laid before him all the difficulties I was capable of, as that of lying under the fort,
and their man-of-war a little distance off, with a very rocky harbour to get out of;
all which seemed to have but little effect on him.
So I thought it was best to consult my own safety; for if there was a skirmish I should,
if I stayed there, be in the midst of it.
So I went down to my old lodgings; but could find no rest for my body,
my mind being very uneasy.
I therefore crept out again, all being still in the ship, and but few upon deck.
I went into the cabin, where I found them as I left them;
but having a little more courage than before,
I told the captain I was resolved to hinder any disturbance if I could; adding,
he surely was not in his right senses to think of any such thing, as his men, I supposed,
knew nothing of it.
He said I was mistaken, for he had told one or two of them in the evening,
and they would acquaint all the rest, and he could have them all up in a few minutes.

It was now about midnight, and his men, I suppose, thinking it high time to get to work,
came upon deck without calling, and seemed to be in high spirits,
for they talked cheerfully, and I thought,
gave several signals to their master that they were ready.
I was in a great strait how to act,
but thought it would be best to endeavour to keep peace if I could,
having said as much as was necessary.
I therefore sat me down close by him,
with an intent to lay hold of him if he offered to take up a weapon,
which was very nigh at hand.
Great strugglings were in his mind, as he himself afterwards confessed.
He often was just upon the point; but the Lord, in his great mercy interposed,
and my mind began to be calm and still, and all fear was taken away.
I then looking at him, saw his countenance became more composed and solid.
I asked him if he would not go to bed.
He threw down his pen and said he would.
The young Frenchman sat by all this time, but perceived nothing of their design.

The night was pretty far spent, and the men, who had walked the deck a considerable time,
thinking nothing would be done, went down to their beds;
and when I had seen the master settled in his,
I lay me down upon a bulk-head of the ship, which was so narrow,
I could only lie upon my side, there being nothing better in the cabin that I could find.
But my mind being easy after the pain it had been in, I fell asleep.
It was a very cold night, and the partition of our cabin was but canvass.
When I awaked I was stiff, but I did not take cold.
The Lord was pleased to preserve me, though I often said in my mind,
I did not think myself worthy,
and more especially because he had allowed this great exercise to come upon me; which,
I several times was made sensible it would have been a light
matter with him to hinder if he had seen fitting.
I often cried to him in the secret of my heart,
that if there was any iniquity lodging in me, he would be pleased to take it away;
and if my going was not consistent with his will,
that he would be pleased to show me wherein I had missed my way;
that I might not bring a reproach upon the truth,
and a trouble and exercise upon his people.
It was not long we had to stay among this sort of company,
for by the time the sun was up, the captain,
with several more such as himself came aboard;
also two of their friars in their odd sort of dress;
I suppose to see what they could get in the scramble.

When breakfast was over,
as several of us were to be searched before they took their leave of us,
those appointed to do that business stayed in the cabin.
The captain and several others went out, and I among the rest,
but was soon called in again, for they searched me one of the first.
When I came in they told me they wanted my money.
I said not much to them, but thought if they got it they should take it from me;
so they began to search me, and took what they could find,
which was but one guinea in money, and all other things they found about me of any value;
but my wearing clothes they gave me again.
When they had searched me as long as they thought fit, they let me go,
but they were not contented,
for they had got it into their minds that I had a considerable sum of money,
and a gold watch; therefore I was no sooner gone out, but they ordered me in again,
and I was searched in every part where they thought any money could be concealed.
I was so grieved with them, I could not hold my peace, but said,
they pretended to be gentlemen, and men of honour,
but now they did not appear to be such;
for it was good works which made men truly honourable;
and as to what they could do to me, I said, I was not afraid of.
Indeed, all fear was taken away from me; I did not seem afraid of my life,
but whether I did well in telling them so, I afterwards queried;
for I thought that courage was only given me for my own support,
and not to lavish away at that rate.
However, I came off pretty well,
for they let me put on and carry away as many clothes as served to keep me warm.

We were on board eleven days, and then were landed near a town called Roscone.
When we came to it, many people were gathered to see us,
among whom was a mixture of black coats; two of them came to me,
and one taking hold of my sleeve, asked me as I supposed, what religion I was of,
and whether I could speak Latin.
I told them, as I was a prisoner they had no business with me,
and I did not incline to have any discourse with them;
therefore desired they would not ask me any more questions.
They turned off, saying, "`He is for no controversy.`"
If I had been asked an honest question concerning the hope that is in me,
I believe I should have had an answer according to truth;
but pearls ought not to be cast before swine.

As soon as I had got quit of the two priests, there came a man to me,
who seemed to be of some considerable account in the world,
and said he was sorry to see me there; but it was the fortune of war.
He wished me safe in England again.
He went to one of his acquaintance who lived in the town,
and after some discourse he came and invited me and Riddell, with two others,
to his house, and set before us such as they had, and desired us to eat and drink.
There was also a woman in the house much concerned
about our having to walk to Morlaix that night,
which was twelve miles, and sent to hire horses, but none were to be had.
She therefore gave strict charge to the soldiers that conducted us,
to hire horses at the next place, and she would pay the charge.
I wish many may follow her example in being kind to strangers;
for what she did I thought was of great service to me.
The soldiers hired horses for four of us when we came to the next town,
which was four miles.

This town was pretty large, and there were many spectators.
That they might have a full view of us, the soldiers had us into a convenient place,
and stood round us at a little distance.
The people gathered so thick, they could scarcely stand one by another;
and in this posture they kept us about half an hour.
Then they had us to an inn, where we were put into a large chamber,
and food and drink were set before us.
But before we were well sat down, several men and women of the upper rank came in;
the rabble stayed mostly below.

While we were eating some of them turned up my coat laps
and examined what my clothes were made of as well they could,
and commended them for being good.
They seemed not to take so much notice of any as they did of me; often pointing at me,
saying, I was a minister, a priest.
Several gay women sat behind the table,
where they had opportunity to look at me as much as they pleased.
They were very light and airy, which I showed some dislike to,
and told them I had heard the French used good manners, and knew how to behave well;
but it could not be said so of them,
for it was not good manners to come into our room without leave, and when they were in,
not to behave soberly and well.
I soon perceived.
I had an interpreter, for some among them understood English, and informed the rest;
upon which they left the room, and it was soon pretty clear.
After them came in several young men, who both looked and behaved well.
I had nothing in my mind against being free, and looking pleasantly on them; for this,
when seasonable, has a good effect.

The next place we came to of any account was Morlaix; it was night when we got in,
and we were obliged to stand and sit in the street till
they got orders from the commissary what to do with us.
I thought the time very long, more on account of our poor men than myself;
for they had walked till they sweated, and some of them were ill.
To sit in the street an hour or more in a cold night,
I thought was almost enough to give them their death.
When orders came, they were to take us to prison; but a merchant, one Forney,
who was agent of the prizes, met us in the street and took Riddell,
the two man-of-war`'s-men and myself to a tavern,
where we had what we pleased to call for, but not at the cheapest rate.
Our landlord was an Irishman, and I perceived had a very good opinion of himself.

After we had supped, and he had informed himself what I was,
he entertained us with a dish of as unsavoury discourse
about religion as I thought I had ever heard:
and what made it more irksome, he held it very long.
He brought a book, out of which he said he taught his children, and as he read,
some of our people were so weak as to commend it, which made him more eager.
I do not remember that I either answered any of his questions,
or made any objections to what he said;
but when he told me he intended to bring some of my brethren to see me,
meaning the priests,
for he said they would like to have some discourse with
me--I told him he need not bring any there upon my account,
for I did not want any of their company; so that was put an end to,
for they never came to me while I stayed in Morlaix.
While I was here, the young man came to see me,
who took care of me the first night I lodged aboard the privateer,
and saluted me in a very friendly manner.
This young man took more notice of me than any other all the time I was aboard,
and when they were stripping and searching me, he stamped upon the deck,
and showed great resentment, as Riddell told me, and knowing he had not wronged me,
could cheerfully come to see me; but the others who had, did not care to see me,
and though I often met them in the street, they endeavoured to shun me,
and would not look me in the face if they could avoid it.
I thought it was a brave thing to have a conscience
void of offence both towards God and men.

We were brought before one of their chief officers, called the commissary,
to have our names entered, and such as could not find bail must go to prison.
This man and his wife took great offence at my hat being in its place,
as likewise did the commissary at Roscone, who was an old man,
and ill of the gout upon his bed.
But several capital people of the town being present,
he was much displeased because I did not give them
that honour which was none of their due.
When I had given in my name I soon quitted the room.
This commissary was a young man, and several were in the room with him.
I had not asked anybody to be bail for me, for I was easy,
and the thoughts of the prison did not terrify me,
though we had heard a very dismal account of it; however, Forney,
whom I mentioned before, after he had called Riddell aside and asked him concerning me,
ventured to be bail for me.
I stayed a little while in the room after our people were withdrawn,
and looked at the great man as he sat in his chair,
and thought his countenance was somewhat milder,
and he spoke pretty kindly to me when we parted.
It was said he was very bitter against all the English,
and had uttered many harsh expressions against them; but his glass was then almost run,
for he lived but a little while after this.

Forney, who had passed his word for me, being agent, had my papers and letters,
which I found he did not choose to part with, except my certificate and letter of credit,
and another paper or two, which he did not think worth while to keep.
I perceived he was a selfish man,
for after he understood my little money that I should
need was not to come through his hands,
he came to me, and with an unpleasant tone,
told me he would not stand bound for me any longer.
I said I did not intend to give him any offence in employing another to do my business,
namely, Charles Sermanson, a merchant, who was of great service to me afterwards,
when I came to be acquainted with him.
When he heard Forney would not be bound for me any longer,
he said he would be bound for me as freely as he would for his own brother.
So I was still kept out of prison.

While we were here we were examined at the admiralty office,
where they asked many questions,
and I thought if I had been enough aware of them
I should have come better off than I did.
Before they had us into the room where we were examined,
they had something of the form of an oath.
I told them I could not take it, being against our principles.
After some discourse about it, they not being willing to let me pass without examining,
had me into their room, and asked me my name and place of abode, whether I was married,
and what children I had; to which I answered.
They asked what preparations were making in England for war?
To which I answered, as I did not concern myself about such things,
I should say nothing about them.
They asked other questions about the manner of our being taken,
and what was taken from me, and about our ship and cargo.
Then after a pretty long pause, one said, "`Now I have some close questions to ask you,
but you must not be angry.`"
I was silent, not knowing how I should come off.
He then asked whether I was a minister?
I said I did not choose to be put under that denomination.
He said, "`What then?`"
I told him my business when at home, was to look after and feed cattle,
and such in our country were called graziers.
He asked me what I was going to do in Pennsylvania?
I said, to visit my friends.
Whether I knew anybody there?
I said I was acquainted with but a few.
Whether I was sent by the Quakers?
I told him I was not; though I had their approbation therein.
He then asked me whether or no the Quakers would fight if they were attacked by an enemy?
I said it was not my business then to tell him whether they would or not;
it was enough for me to answer for myself.
"`Then, said he, if you were smitten on one cheek, would not you turn the other?
Or, if they took away your coat, would not you give them your cloak also?`"
I said it was so declared in Scripture,
but I had not freedom at that time to answer those questions.
He asked me no more questions at that time, that I remember.

About this time I suffered much in my spirit; the reason is best known to the Lord.
I was heavy and sorrowful in my mind both night and day for some time,
and much afraid lest I should bring dishonour to truth by my unfaithfulness,
or some slip or other that I had made, or might make,
for lack of care and watchfulness in that strange land, separated from my brethren,
and deprived of all outward help and comfort.
But this to me was a profitable season, for I found the fear of the Lord,
which was then in my heart, did preserve me from evil, and from falling into temptation.
Though such company as I had was very unpleasant to me,
and I thought myself unfit for conversation; yet, when by honest inquirers,
I was asked questions concerning our faith and principles,
I was helped in the openings of truth,
to give them an answer concerning the hope that was in me; Scriptures freely opening,
and all things being brought to my remembrance, sufficient to put to silence,
and stop the mouths of gainsayers.

While I stayed in Morlaix, Charles Sermanson, before mentioned,
who often invited me to his house, one evening as we were in discourse,
asked me why I went abroad in such troublesome times?
I told him I believed it to be my duty;
for nothing else would have induced me to leave all that were near to me in this world,
as wife and children, but a sense of duty to God,
and obedience to what I believed he required of me; for as to outward gain or advantage,
I had nothing of that in my view, for such as have freely received must freely give.

Thus setting forth the nature, call, and qualification of the true ministry,
I saw it had some reach upon him and his wife,
who sat by and desired that he would interpret to her what I said.
When she understood I had left a wife and children behind me,
she said that could not be consistent with the will God.
I signified she did not consider Christ says: "`He that loves father or mother,
wife or children, houses or lands, more than me, is not worthy of me.`"
I took the liberty to reprove her husband, for taking the great and sacred Name in vain,
which I suppose made some alteration in his countenance.
She then asked him what I said.
When he told her, she said I had done well, for that was his great weakness,
and she hoped he would take notice of it.
I said, by turning our minds to the light of Christ in our hearts,
which reproves for sin, as we came to yield obedience to it,
we should be helped to overcome our weaknesses.
She said I was a saint, and had overcome the temptations of the world.
I said, What I am, it is by grace.
I have nothing to boast of, and by grace I am saved out of many temptations of the world;
yet was a man of like passions, and liable to many weaknesses, as they were;
and was no longer safe than while I kept upon my watch.

My mind was opened to point out to them the way of salvation.
Scripture being brought to confirm the sufficiency,
work and operation of the grace of God upon the hearts of the children of men;
with the saving help there is in it, as obedience is yielded unto it.
It was a seasonable opportunity.
Finding freedom, I let him see the certificate I had from my friends.
When he had read it, he said he liked it very well.
I told him something of the good order we had among us,
which he seemed to approve well of;
but said he could but admire that I should take so
much pains without any view of outward advantage.
I told him what I had said was the truth.
He said he did believe it was.
"`But, said he, our priests would not go across that room without being paid.`"

Perceiving that what had already passed had some good effect,
for the man was very loving,
and his understanding measurably opened to distinguish between the true and false ministers,
I took my leave for that time, and went to my quarters, which were at a tavern,
where I was for several days, and had much company of various sorts.
As I appeared to them somewhat singular, they wanted to know what I was,
and such as could speak English would ask me questions;
and as I found freedom I answered them.
One came as I was sitting in a room, there being a pretty deal of company,
and asked why the Quakers would not fight?
I told him the weapons of the primitive believers were not carnal, but spiritual,
and mighty through God, to the pulling down of sin and the strong holds of Satan;
and such as are now come under the peaceable government of the great King of kings,
who said, if his kingdom had been of this world, then his servants would have fought,
cannot fight with carnal weapons,
though there should seem as great a necessity as there was
when our Lord was like to be delivered to the Jews.
I had to open several passages of Scripture,
which set forth the peaceable government of Christ, who came not to destroy men`'s lives,
but to save them; and that it was not the lamb`'s nature to tear and devour,
but the wolf`'s. This opportunity was seasonable,
the people were very still and attentive.
He that asked me this question had often been with me, and had asked many questions,
but was now silent, and seemed to go away satisfied;
for the power of God was over them at that time.

After some time, I was, with some others who were prisoners at large,
ordered into the country about thirty miles, to a town called Carhaix.
Charles Sermanson supplied me with what money I needed,
and also recommended me to a friend of his there, one John Grace, a counsellor at law,
who, during my stay, showed several tokens of his regard and hearty friendship,
after he and I came to be acquainted; though I may say with safety,
I never sought his or any other`'s favour by any indirect means,
or in a way truth did not admit of.
I went to his house in the evening, and he taking the letter with his hat off,
made a bow, but I not returning it as he expected, he,
with an earnest look and somewhat of an unpleasant tone, said I might go to the tavern,
and he would come to me in the morning.
He did so, and told me,
as I had been recommended to his care by his good friend Charles Sermanson,
he would do the best he could in providing me a private lodging;
and any other service he could do me, which lay in his power, should not be lacking.
I told him I was obliged to him,
and was glad to find him and others of his countrymen
so well disposed to be kind to strangers;
and as I was a stranger, and also a prisoner, I should be glad of his assistance.
He said he was glad he had the opportunity of assisting his fellow creatures,
for he looked upon it to be no more than his duty.
Then we walked into the town, where he provided me a chamber,
and I had everything found me that was necessary.

My new landlord took great notice of my behaviour, and, I suppose,
at first did not know how to behave himself towards me, that I might not be offended;
for being poor, he was glad of a little money.
He could speak no English, and I but little French, so we could have no conversation;
but he told one of the Englishmen who spoke French, that I did him good,
though he could not understand me.
He was a peruke maker by trade, and when he had left work in the evenings,
he and his wife would come and sit with me a considerable time in silence;
which was not disagreeable to me; for sometimes, I believe,
we were favoured with good when we sat in silence.
His wife was a religious woman, and of a solid, sober behaviour, so far as I ever saw.
I stayed in their house three months and then took lodgings in another place;
three young men in like circumstances with myself, desiring very much to be with me,
and they not having room for us all, I left them.
As the young men behaved well, their company was agreeable;
two of them being friends`' sons,
though they did not in many things take up the cross as they ought to do,
yet their behaviour to me was such as gained my love and affection.
One of them soon after died in the French prison, being, when taken,
on his passage to Rhode Island, where his parents lived, at whose house I afterwards was,
and found them very sorrowful, for they had lost three of their sons,
two at sea and one in prison.
As these things affected and made some impressions upon my mind, I made a few remarks.

John Grace the counsellor, after a little while, became very loving,
and had me often to his house, it not being far from my lodgings,
and I found myself very free to converse with him, and told him in freedom at one time,
if he had anything in his mind to ask concerning our Society or principles,
I would have him be quite free,
for I should be willing to answer honestly according to the best of my understanding.
He said he understood we did not baptize with water.
I told him the apostle Paul says, "`There is one Lord, one faith,
one baptism;`" and water, how or by whomsoever administered,
is only sufficient to put away the filth of the flesh,
but not able to wash away the sin of the soul.
The same apostle said, "`He was not sent to baptize,
(he there must be understood with water,) but to preach the gospel,
which is the power that baptizes into the one Spirit.`"
He further says concerning himself,
that he was not a whit behind the chiefest of the apostles;
yet he thanks God he had baptized no more than the few he recites,
which he would not have done if baptism with water
had been the one baptism essential to salvation.
He said he thought there ought to be something done to children by the minister,
to initiate them into the church.
I said as to our not being in the practice of sprinkling children with water,
or signing them with the sign of the cross, as it was not Scriptural,
we could not be justly blamed for the disuse of it.
He then said, if he at first had put on the priest`'s gown instead of that he then wore,
he should have thought it his business to search more into the Scriptures.
I told him I took him to be a man of such understanding as very well to know it ought
to be everyone`'s business to search into the things that belong to their own peace.
He said it was true, but they had men who were learned, whom they paid,
and he looked upon these to be his teachers; and as for him, he was but a hearer,
and if they deceived him,
it would be the worse for themselves--they could not deceive God.
I said it was true, they could not;
but as the salvation of the soul is a thing of so great importance,
we should not place our dependence upon others; and as to teachers,
we might know them by their fruits; for, according to Christ`'s own words,
"`men do not gather grapes of thorns, or figs of thistles.`"
He further says to his ministers, "`freely you have received, freely give.`"

As to those of polluted lips, I thought they could not profit the people at all.
He said there was no Scripture that forbade marrying,
and he thought their priests wrong in that; for they did not keep themselves chaste,
but deluded and deceived many poor young women.
I said it was great pity any should be deprived of the benefit of the Scriptures,
for all ought to have liberty to try all things,
that they may hold fast that which is good;
for it is dangerous pinning their faith upon other men`'s sleeves,
"`If the blind lead the blind, they will both fall into the ditch.`"
He then said he should be glad to read some of our authors,
which I gave him some expectations of sending, if I lived to return home.

Some time after this, he sent for me to dine with him,
when I expected he would have had some priests with him, but he had not;
though he told me he had invited one of their clergymen to dine with him,
and acquainted him I was to be there, but he desired to be excused, alledging,
he thought I should be offended with his company.
I said I should not, if he was a religious, sober man.
I was not had before the commissary or chief magistrate, at my first coming here,
with the rest of the prisoners, but this counsellor gave in my name,
and when they went to receive the government`'s allowance, I went,
not having enough to support me without.
But hearing the commissary had uttered some very bitter expressions against the Quakers,
and me in particular, for not putting off my hat,
as he had observed when I met him in the street, I had an inclination to pay him a visit,
which I acquainted a young man with, who could interpret for me.
We found the commissary in the street.
The young man told him I was come to see him, or pay him a visit.
He looking earnestly at me, after a pause took us into a room,
and before I could say anything to him, asked me why I did not put off my hat.
I told him uncovering our heads was what we did when we prayed and addressed the Almighty;
but to do it to our fellow creatures was against our consciences.

The answer, though short, I perceived satisfied him, for his haughty countenance fell,
and he then spoke mildly, and said he had heard we did not baptize our children.
I said we did not use water baptism.
"`What do you then, said he, instead of water?`"
I said, the one baptism, which we believe to be saving and essential to salvation,
is spiritual--that of fire and the Holy Spirit; and as to little children,
they are heirs of the kingdom of heaven without water, or the help of any mortal man.
I told him I had heard he said something against me,
but I came in good will to pay him a friendly visit,
for I had a mind to speak with him myself.
He then took me by the hand, saying he would not do me any hurt,
but all the service that lay in his power.
I took my leave of him with thankfulness, that truth had thus far prevailed,
and the young man was well satisfied; for he was somewhat in fear before we went,
having heard what the commissary had said concerning me.
Ever after when I met with him, he looked pleasantly,
and I believe never any more took offence at my hat.

Charles Sermanson, while I was here, wrote me several kind letters;
and mine which I wrote to England, he took care to send to his correspondent in London;
by whom also my letters from home were safely conveyed to me,
which made my confinement much the easier, as I could often hear from my wife and family,
and they from me.
After I had been confined about five months, I was released: my passport coming to hand,
I showed it to John Grace, and he went with me to the commissary, who readily signed it,
expressing his gladness that I had got my liberty and was going to my family.
He also gave leave to several of my fellow prisoners,
who were desirous to accompany me to Morlaix.
The 23rd of the fourth month I took my leave of the counsellor and his family,
with many others, both French and English,
who came to see me in a very affectionate manner.
When I came to Morlaix, I found a Dutch vessel bound to Ostend.
Charles Sermanson agreed with the master to set me on the English coast,
if the wind would permit, which happened well the 28th of the fourth month, 1757.

When I came to London, I found several friends very glad to see me,
having had a near sympathy with me in my exercises;
and I saw the Lord had been my helper and deliverer,
in that he had been pleased to bring me safe to my native land; and not only so,
but I found friends as nearly united to me as ever; which was a great comfort.
For I had been afraid lest they should stand at a distance from me;
but magnified be the great Name forevermore, I found all well in that respect,
and likewise when I came to my own habitation, which was on the 11th of the fifth month,
1757.
