== Chapter II

I soon set out again for the yearly meeting in London,
which began the 25th of the fifth month this year.
My brother Maw and two other friends accompanied me.
It was believed I was intending to proceed again to America;
but I could say little to it when asked, till the yearly meeting was over,
and friends mostly gone out of town.
I was then made sensible it was my duty again to make preparation to set forward;
a ship being nearly ready to sail for Philadelphia.
I then acquainted friends with it, who left me to my liberty,
expressed their unity with it, and made all things as easy for me as they could.
For which my spirit was bowed in thankfulness to the great, good,
and wise Disposer of all things, who can dispose the minds of his people as he sees fit;
and who ever will, I believe, make way for all that put their trust in him,
that his requirings may be in all things duly answered.
I took my leave of my wife and family in a solemn manner,
not knowing I should see them again in mutability.
I also settled my outward affairs in such order as I thought might be for the best.

The 19th of the sixth month, 1757, I left London,
several friends accompanying me to Gravesend.
The vessel being just ready to sail, I took leave of friends,
and followed her in a small vessel as far as the Nore,
two of my kind friends still accompanying me, namely, John Sherwin and Thomas Wagstaffe,
I went on board the ship and they returned to London.
We arrived in the Downs the 21st, and waited for a convoy;
it being a time when much shipping were taken by the French,
the people were not willing to go without men of war.

I went on shore while here, and found a small family of very sensible friends,
of which I was glad.
The 23rd we weighed anchor, being in all about sixty sail.
We lost sight of land the 8th of the seventh month, had a good passage,
and in ten weeks from London we got safely to Philadelphia.
Here I found several friends from Europe in the service of truth.
We were truly glad to see each other, and had comfortable meetings together;
blessed be the name of the Lord.
I have great cause to be truly thankful,
and in humble reverence to praise his great and everlasting Name,
for many deliverances both by sea and land.
I may in truth say, his name has been to me a strong tower,
and there I have run and found safety.
For though he allows his servants to be tried, as in the furnace of affliction,
he will not leave nor forsake them; but his arm has been made bare for their deliverance,
and he has granted them the petition of their souls.
Glory and honour be given to him, and that forevermore.
I stayed in and about Philadelphia till the yearly meeting was over.

The 5th of the ninth month, 1757, I went into New Jersey, John Pemberton accompanying me.
We had a meeting at Haddonfield; from there to Chester, and had a meeting there also,
both to good satisfaction.
We lodged at Edmund Hollinshead`'s, and on first-day were at Evesham meeting,
which was attended with the seasoning virtue and power of Truth.
We went that night to Burlington, and attended the monthly meeting on second-day,
which I thought was to general satisfaction.
I lodged at John Smith`'s, a substantial friend,
and a very serviceable man in the Society.
Here John Pemberton left me.

I went next day to Ancocas, it being the 4th of the tenth month, and third of the week.
We had a meeting there, which was hard in the beginning, and dull;
but that spirit of earthly mindedness, which had too much prevailed,
was testified against, and truth, I think, did in a good degree spring up over all;
praised be the great Name forever.
The fourth of the week, accompanied by another friend, had two meetings at Mount Holly,
both to pretty good satisfaction;
we lodged at Josiah Foster`'s. Fifth-day we had a meeting at a school house,
which was large, and though it held long, the people were very quiet;
we lodged at William Smith`'s. Sixth-day we had a meeting at Old Springfield;
first-day at Mansfield.
It was a large meeting, but the minds of the people hankering much after words,
the spring of life that had run through me, being in a great measure stopped,
a cloud came and covered my tabernacle.
I saw it was safest to stand still.
We lodged at Peter Harvey`'s, a kind and steady friend.

Next day, the second of the week, and 10th of the month,
we had a meeting at a school house in the neighbourhood, which was small,
but in some degree satisfactory;
we lodged at William Smith`'s. Had a meeting at Upper Springfield on third-day;
at Freehold on fourth; Crosswick`'s on fifth; Bordentown on sixth,
and Trenton on first-day; we lodged here at William Morris`'s. From there to Stonybrook,
and had a meeting on the second-day of the week and 17th of the month.
We lodged at James Clark`'s. In this place they had
been hurt and scattered in their minds;
as also in several other places, where a striving and a dividing spirit had got in.
From there we went to Robins`' meeting on third-day,
which was not so satisfactory as could have been desired; some being restless,
the meeting holding long.

We went from there to Squan,
and had a meeting there on fifth-day among a company of poor dark people.
Then to Shrewsbury the 22nd of the tenth month,
where was a meeting for ministers and elders.
The meeting on first-day was very large,
and considering the great numbers of people of all ranks, was quiet.
Second-day it was a good, solid meeting, truth prevailing over all;
praises be given to the great Name forever.
The Son of righteousness did arise with healing in his wings,
and my soul was delivered as out of the pit; for I had been ready to despair,
and thought I should have been overcome by the enemy.
Great horror and darkness was over my understanding for a time;
but the Lord did send his light and his truth, and caused it to shine upon my tabernacle;
and I had to declare of his mercy and goodness towards the children of men,
and to invite them to come and see for themselves,
what great things the Lord will do for them that trust in him.
This great meeting ended well,
and I was truly thankful to the great Master of our assemblies.
We lodged at Joseph Wardel`'s, a worthy friend.

On third-day we came back to Crosswicks, and lodged at Thomas Middleton`'s,
Next day to the widow Andrews`', where my companion was taken ill.
Here I left him, after staying one night, and went to Haddonfield with Isaac Andrews,
and lodged at his house one night, and so to Philadelphia,
where I stayed till their quarterly meeting.
We had several comfortable opportunities together.
John Hunt and Christopher Wilson from England were here, and had good service.
I stayed about Philadelphia, attending meetings as they came in course,
both for worship and discipline, until the 15th of the eleventh month,
when I set out towards the southern provinces, Thomas Lightfoot accompanying me.
We went to Chester, and were at their youths`' quarterly meeting,
which was a time to be remembered by many of us.

We visited the meetings through Chester county till we came to Nottingham,
and were at the monthly meeting, John Hunt also being there.
It was a suffering time to me,
I being sensible many were worshipping only in the outward court,
whose dwelling was in the form without the power; such cause suffering to the true seed.
I stayed meeting with them on first-day, and was led to speak closely to several states,
and left them pretty easy in my own mind.
I lodged at John Churchman`'s, and had a meeting at West-Nottingham on third-day;
at Little Britain on fourth-day; here several Presbyterians came in with their priest,
who took down in writing what I said; though I perceived not that he was writing,
till I had nearly done speaking.
When I sat down most of them went out, but he stayed;
and after a short space I had to say, "`The time shall come,
when the dead shall hear the voice of the Son of God, or they that are dead in forms,
and they that hear and obey shall live; and that Christ is the resurrection and the life,
and he that lives and believes in him, though he be dead, yet shall he live.`"
I did not enlarge much upon it; but the meeting broke up in a good degree of life,
and the priest went off with his company.
Friends thought there was no danger of any ill coming of it,
but I was afraid lest truth should suffer.

I rode that evening after meeting to William Downing`'s, who had a large family,
with whom we had a good opportunity.
From there we came to Sadsbury, where I had a meeting, and in the openings of truth,
had closely to speak to the states of many.
From there I went to Lampeter, where I had two meetings; and so to Lancaster,
and had a meeting with the few friends that lived there.
We lodged at Isaac Whitelock`'s; and after having a meeting at James Wright`'s,
we crossed the river Susquehanna and went to York, where a few friends dwelt,
and had a meeting among them.
We quartered at Nathan Hussey`'s.

Our next meeting was at Newberry; it was silent, but to my satisfaction.
We passed through Warrington, but had no meeting,
it being the youths`' quarterly meeting at Huntington,
where we had an edifying time together.
We had also meetings at Monallen, John Evans`'s, Pipe Creek, Bush Creek, and Monoquesy.
Then crossing Potomac, we came into Virginia to Fairfax;
where we had a meeting on the second day of the week and 12th of the twelfth month.
It was a good meeting, truth having the dominion;
magnified be the great name of Israel`'s God, and that forevermore.
We lodged at Mary Janney`'s, a discreet, orderly woman, who had several sober,
well inclined children.
From here we went to Goose Creek, and had a meeting on third-day: it was well.
On fourth-day we had a meeting at David Pole`'s, several friends accompanying us.
I had a travail in spirit that truth might not lose ground,
finding a spirit of ease had greatly prevailed in many of the professors of truth,
to the sorrow of the honest-hearted.
We left David Pole`'s house on fifth-day, and rode over the Blue Ridge,
or Blue Mountains, where the Indians had done much mischief, by burning houses, killing,
destroying, and carrying many people away captives;
but friends had not hitherto been hurt;
yet several had left their plantations and fled back again over the Blue mountains,
where the lands had been rightly purchased of the Indians.

Things seemed dreadful, and several hearts ready to fail.
We proceeded on our journey, and came within six miles of Winchester,
where the English had a fort.
On sixth-day we had a meeting at Hopewell, which was an open time.
I found my mind much engaged for the poor suffering people,
but had to tell them their greatest enemies were those of their own houses.
The meeting ended well.
We lodged at Joseph Lupton`'s, an ancient friend, who with his wife was very loving to us.
The Indians had killed and carried away several within a few miles of their habitation,
yet they did not seem much afraid;
for they said they did not so much as pull in the
sneck-string of their door when they went to bed,
and had neither lock nor bar.
We had a meeting at Crooked Run on first-day, the 18th of the twelfth month.
It was a good meeting, the Lord favouring with his living presence.
Glory be to his great Name forever.

On second-day we set forward through the woods, and over the hills and rocks,
crossing several large creeks.
We came in the evening to a man`'s house, called Moses Mackoy,
and had a meeting there next day.
They were an unsettled people, yet assented to truth;
but were not fully convinced in their minds concerning the sufficiency of it,
having an eye to outward shadows: I left them in good will.
On fourth-day we rode about thirty miles to Smith`'s Creek,
where we had a meeting on fifth-day, at the house of William Carroll.
It was silent, though they had sent notice several miles, and many came.
I told them, though I had nothing to communicate by way of preaching or declaration,
yet I found freedom to have another opportunity at a proper time and place;
which I had next day at the house of John Mills, about ten miles off,
somewhat in our way.
The meeting was to good satisfaction.
The Indians had killed and taken away people within two
or three miles of this place not many weeks before;
but the Lord preserved us in our journey.
Thanksgiving and praise be to him, and that forever.

Seventh-day we set out towards the south parts,
and lodged that night at the foot of the Blue Mountains, at a friendly man`'s house,
having two friends to conduct us.
Next day being the first of the week, we crossed the mountains,
and towards evening came to Douglas`'s, and had a meeting with the family.
The 27th, and third of the week, we had a meeting at Camp creek.
It was a pretty open meeting,
though the sense of good is almost lost among them in that place,
and their states much to be lamented.
We lodged at Charles Moman`'s. Next day we rode fifteen miles,
and lodged at Francis Clark`'s, and had a meeting at Fork creek.
Many people came, and sat with great attention, and the meeting was solid.

From there we went to Genito, where we had a meeting, and many people came,
but it being silent, they seemed dissatisfied.
As I had nothing to say,
I was glad I could be made willing to be what the Lord saw fit to allot me.
We lodged at Jane Watkins`'s, a widow woman.
She received us kindly, and had several loving and well inclined children.
We had a meeting at Cedar creek on seventh-day, the 31st of the twelfth month, 1757.
It was a satisfactory and good meeting.
Truth had the dominion, praises be to the great Giver of every good and perfect gift!
I lodged at William Stanley`'s.

From there we went to Caroline, where the meeting was on first-day,
the 1st of the first month, 1758.
It was a large and good meeting.
The states of the people were so spoken to,
that through the Lord`'s goodness and condescension, I hope it may tend to his honour,
and to the help of his poor creatures.
We lodged at Morner Cheagles`'s, and also at John Cheagles`'s, one night.
Next meeting we were at the Swamp.
It seemed to me, as I travelled along through these parts,
true religion was much lacking among many of the professors of it.
I lodged at William Johnson`'s. The next meeting was at the Black creek.
It was a good time to me, and I hope also to some others; praises be to the great Name!
On the seventh of the week, and 7th of the month, the meeting was at White Oak Swamp,
being monthly meeting, and then rode to Curies, and lodged at John Pleasants`',
a very kind friend.
We were at their meeting on first-day.
The third of the week and 10th of the month, had a meeting at Wain Oak,
fourteen miles from Curies, which was satisfactory.
We lodged at John Crew`'s,
and on fourth-day came back to John Pleasants`'. On fifth-day we rode to Robert Langley`'s,
near Petersburgh, and on sixth-day had a meeting at the house of a friend, called Butler.
It was an acceptable time to some.

After meeting we went to Robert Langley`'s, where we were kindly entertained.
On first-day we were at Pattison`'s meeting, which was a low time with me;
yet truth in some good degree prevailed.
On second-day we came to Burleigh, and lodged at John Honeycut`'s,
and had a meeting at Burleigh on third-day, which was to some acceptable.
We lodged at Wike Honeycut`'s, and were at the monthly meeting at Surry-black Water,
where we had good service for truth.
They being in the mixture,
permitted people of other societies to sit with them in their meetings of business.
I was grieved,
and could not be easy till I had desired those to
withdraw who did not make profession with us,
both from the men`'s and women`'s meeting.
I had to recommend to the oneness and simplicity which truth led into,
and to keep their meetings for discipline, in that wisdom, power,
and authority that they were at first set up in;
that they might not join with the world`'s spirit, but keep themselves separate,
and in the wisdom and power of God, keep the authority,
and bear rule over those that were got into the mixture,
and were for having those that did not profess with us to
sit with them when they transacted the affairs of the church.
For some that professed truth had encouraged this practice,
which tended to weaken the hands of the honest-hearted,
they not having found liberty and freedom to speak so closely to their brethren,
as need required.
Joseph could not use that freedom,
and unbosom himself to his brethren in such a manner as the case required,
till the Egyptians were gone out.
I was glad I was there, for truth had the dominion in the end.
We lodged at Anselm Baley`'s. I visited all the little
handfuls scattered up and down in these parts,
and often had service in families.

I met with Samuel Spavold, who likewise was much engaged in the service of truth.
His labour of love in the work of the gospel was indeed great in this part of the world;
those of other societies being much reached by his ministry.
We were truly glad to see each other; for as iron sharpens iron,
so does a man the countenance of his friend.
We had several comfortable and confirming seasons together,
especially at the quarterly meeting held at Black creek, for that part of Virginia;
many Friends from various places being there.
I was glad to see them, but what made us more glad, and brought us nearer to one another,
was, because the Lord favoured us with his presence,
and filled our hearts with his pure love.

Having visited nearly all the meetings in this province, I took my leave of many of them,
so far as I could see them.
Taking a few meetings in my way, in company with Samuel Spavold,
I proceeded towards North Carolina,
but left him to visit some meetings he had not been at.
I went to Pineywoods, near Perquimons river, in North Carolina;
and had a meeting at Pineywoods the 9th of the second month.
It was large, and attended with the overshadowing of divine goodness.
To me it was an edifying, strengthening time, as I trust it was to many more.
We took up our quarters at Thomas Newby`'s; the next day we had a meeting at Wells,
which was the sixth of the week.
On seventh-day we were at the Old Neck, and on first-day at Little river.
This meeting was very large, there being a considerable body of Friends in this part;
and people of other societies attend Friends`' meetings when there are strangers.
I was helped through those large assemblies far beyond my expectation.
I thought myself so unfit, weak and unworthy,
that I was almost cast down in my mind before I came there;
but praises and thanksgivings to Him that helped me,
I left them rejoicing in a sense of the Lord`'s goodness and mercy to my soul.
I lodged two nights at Thomas Nicholson`'s,
who mostly favoured me with his company while I was among them.
Here my companion Thomas Lightfoot, left me, and returned to Philadelphia.
The last meeting I was at here, was appointed for Samuel Spavold.
At Pineywoods we had a solid opportunity together,
many minds being truly bowed to the root of life in themselves, and finding myself clear,
may truly say, I parted with a remnant in pure love, and the unity of the one spirit.

I then set forward towards a wilderness country, where the inhabitants were very thin,
two young men accompanying me.
Our first meeting after we left Perquimons,
was at John Copeland`'s. There were but few Friends,
but people of other societies came in, who had notice;
among whom was an officer in the army.
He came to our quarters in the morning,
and rode about six miles on the road towards the meeting, then turned off,
and said he would go and fetch his wife.
He also brought with him a company of young people,
who were learning to dance at his house, which I did not know till the meeting was over,
and then he came and told me he had invited them to come to the meeting,
and also their master, but he would not come.
I said it was so far well, but it was a pity he should encourage such vanity,
as to keep a dancing-school at his house.
He excused it, saying the man owed him money, and he knew not how to get it,
but by letting him teach his family.
I signified that he had better lose it,
than have his family taught that which would be unprofitable to them;
for there was a woe pronounced against such as did chant to the sound of the viol,
and invented to themselves instruments of music, like David.
He said it was the truth that they had heard spoken today,
but acknowledged they did not walk answerable to it.
I said it was their own fault;
for if they would take heed to the teachings of truth in themselves,
it would lead them into all truth, and consequently out of all error,
and every bye-path and way that leads to destruction.

After we had refreshed ourselves, we passed his house, and he seeing us,
came and invited us in, saying he had entertainment for us,
and should be glad of our company, and we should have a room to ourselves.
I acknowledged his kindness, but as time would not permit, we must proceed on our journey.
We took our leave of him, and I thought he was so reached,
as to be measurably convinced of the sufficiency of the blessed truth;
though his appearance, and likewise his mind being lofty,
he was not willing to submit to the low appearance of it.

Our next meeting was at Thomas Knox`'s, a man lately convinced;
it was in a good degree satisfactory.
We had very difficult roads, through great swamps and across many creeks,
all through the woods; and in many places but little path to be seen.
We came to Fort river,
where there is a meeting settled of such as had been lately convinced.
Many came to meeting,
which was held at Henry Horn`'s. Some of them were unsettled in their minds,
not being founded upon the sure Rock; but such as seek shall find,
and they that dig deep enough will come to the sure foundation,
that the righteous have built upon in all ages of the world.
Henry Horn had been a teacher among the Baptists.
He seemed to be a steady, well disposed man, and had a few words in meetings.
After I left his house, I had a meeting at Joseph Pitman`'s, who, with several others,
was under convincement.
It was an edifying season, many being sensibly touched with the love of truth.
I stayed with them one night, and then went to a small meeting near a place called Nues.
It was two day`'s journey, a very difficult road to find,
and none of our companions had been there before.

After this meeting we went to Core Sound, an inlet of the sea.
We had ninety miles to ride, and were altogether unacquainted with the way,
having rivers and many swamps to cross.
The two young men were still my companions, Joshua Fletcher and Francis Nixon,
who were very serviceable to me through this almost uninhabited part of the world.
We got to Henry Stanton`'s in the night, who took us in and entertained us very kindly.
When we had stayed two days, had a meeting, and rested ourselves,
we set forward towards the next meeting among friends,
which was one hundred and fifty miles.
But in our way we had two meetings among people of other societies.
I had still no guide but the young men, who knew no more of the way than myself.
But such as are used to the woods can find the way
through them better than such as are not.

The first meeting we had after we left Core Sound, was at Permeanus Hauton`'s,
who gave us an invitation to his house, and sent to give notice to his neighbours,
though some lived several miles distant.
We got to his house about the time the meeting was appointed,
where we found seats placed,
and everything in such convenient order for a meeting as I thought I had seldom seen.
His rooms being little, he had placed seals in his court-yard, and under the windows,
so that I believe all could sit and hear without in the least troubling one another.
I thought his labour and good inclination were blessed, for it was a solid time,
and I found openness to declare the truth among them.
I would that all our friends upon the like occasion,
would take this man for their example, in being diligent to invite their neighbours,
and to make room and accommodate them in the best manner they are capable of.
It certainly has a good savour, and is often attended with a blessing.

A steady friend, who had been a member among the Presbyterians,
told me that the care and pains that some friends
took to invite him and some others to meetings,
was one moving cause towards his convincement.
He said he once told a young man who had frequently
invited him to our meetings when strangers came,
that as neither he nor any of his friends came to their meetings,
he thought he would go no more to theirs.
The young man answered very calmly, "`We must not come to you,
but we want you to come to us.`"
"`This,`" said he, "`with the diligence friends had used without view of outward gain,
affected my mind,
that I concluded it must be the love of God in their hearts
that induced them to call and invite us to come to them.`"
This I mention more particularly, because I have seen some that profess truth,
to my grief, very deficient in this respect.
We had another comfortable opportunity in the evening with this man and his family,
and some others, that stayed all night.

Next morning, with the two young men and one more,
who had a mind to go a day or two along with us through the wilderness,
I set forward well refreshed both in body and mind; hard things being made easy,
and rough and untrodden paths being made smooth to my mind.
We had a meeting at George Cowper`'s, whose wife was educated among friends.
We stayed one night at Wilmington, the capital town in North Carolina;
but it being their general court time, and the privateers having brought in prizes,
the people`'s minds were in great commotion,
so that I could find no room or freedom to have a meeting,
though several called Quakers lived there,
but held no meeting except when strangers came.

We crossed a branch of Cape Fear river, and landed upon a great swamp,
which was very rotten and dangerous, by reason of the overflowing of the river;
but the two young men and a negro, whom we hired to help us,
carrying boards from one place to another for the horses to tread upon, in time,
and with much difficulty, we got well over.
We then came again into the woods, where little path was to be seen;
it likewise being rainy, dark weather, we could not tell which way to go,
but rode many miles, hoping we might be steering right;
and just at the close of the evening, before it was quite dark,
we came to a little house, the sight of which was satisfactory, being weary and very wet.
When we called, the man said he kept an ordinary, which we found to be true.
However, we were contented with such as we found, and thankful we fared so well.
We were in our direct road for the place we intended, which was Carver`'s Creek,
where we got next day, the sixth of the week, and 10th of third month.
Here was a small gathering of friends.
We stayed their first-day meeting, and then went to Dan`'s Creek,
where we found another gathering of such as call themselves friends,
but had been much hurt and scattered in their minds from the true Shepherd,
by an enemy that had sown tares.

Here I parted with my two good companions,
who had travelled with me more than five hundred miles.
Being nearly united together, we parted in true love.
This I mention, because the Lord loves a cheerful giver, and those did, I thought,
what they did, with great freedom and cheerfulness, not grudging a little time,
nor a little outward substance, for the sake of the good cause of Truth.
These will not lose their reward, for it is helping forward the work,
as that of opening a door and kindling a fire,
is doing part of the business of the Master`'s house;
and he looks upon it as done to himself, if it is but handing a cup of cold water,
as it is done in a right spirit, it will have his blessed approbation and reward.
I had another companion, providentially, I thought, provided here for me.

William Ferril, a public friend, having heard of my being in the country,
had got himself ready against I came, and had freedom in the truth to travel with me,
till I should fall in with another suitable companion;
which made my travels through those lonely places much easier.
When we left his house, we set our faces towards South Carolina,
having but one meeting of friends to take in the way,
which was settled upon a river called Pedee,
about a hundred miles from the said friend`'s house.
This we accomplished in about two days.
In the night we lodged in the woods.
The few friends were truly glad to see us, they being seldom visited.
We had comfortable and refreshing seasons together,
the Lord owning and favouring with his good presence, strengthened not only the inward,
but the outward man also.
Here I was sensibly affected with such a seal and evidence of peace in my own mind,
that I was fully persuaded I was in the way of my duty;
it made me go on again very cheerfully.
No one can tell how good the Lord is,
but such as have tasted and seen his marvellous ways of working,
and how he can spread a table in a wilderness, for those who, in faith and obedience,
give up to his requiring; for he lets them lack neither inward nor outward food.
There is now, as well as formerly, a little remnant, who, with my soul,
can set their seal to the truth of this; and can say unto him, "`We have lacked nothing,
Lord!`"

Francis Clark, with whom we had quartered, bore us company one day and night in the woods.
We thought sometimes we travelled near sixty miles in a day;
for when we had to lodge in the woods, we rose early and lay down late.
Our friend Clark returned home, leaving us to shift for ourselves;
but my companion having some knowledge of the way, steered, I believe,
a pretty straight course.
When night came, we pitched our tent in a valley where there was some grass,
and a little brook of water.
So when we had eaten such as our bags afforded, and given our horses provender,
and taken care of them, with what little we had,
we lay ourselves down and slept very soundly and comfortably, being wearied with riding.

Next morning we were stirring by the time it was well light, and soon being ready,
mounted our horses; and it was well we did so,
for there came a rain that day which raised the creeks and rivers so high,
that if we had not got over them that night, we might have been stopped for some days.
We travelled till late in the night, and coming to a house,
desired we might have lodgings; but the master of it told us we could not.
We asked him how far it was to another house; he said it was but a mile,
but there was a deep creek in the way,
and he would not go with us if we would give him a great deal of money.
I then very earnestly desired that he would let us stay in his house all night,
and we would pay him for his trouble, and for what we had;
for we had rode almost all that day in the rain, and it was a very cold, rainy night.
He told us he would not let us stay there, and so left us standing outside his gate.
But a young man standing by, seeing and hearing what had passed, took pity on us,
and said, though it was dangerous crossing the waters,
he would lake his horse and go with us which he did,
and we got well through to the place the man had told us of.
After refreshing ourselves with such as the house afforded,
we took up our lodgings in a very cold room, such as I had never lain in before.
But bad as it was, I was glad and thankful we had not to lie out all night in the rain.
I rested well, and in the morning was well both in body and mind.

The fourth of the week we got to the Wateree,
where several friends from Ireland had been settled about six or seven years.
We had a meeting with them, and then, with Samuel Millhouse and my companion,
I set out towards Charleston.
This took us most of three days, it being one hundred and thirty miles.
When we came there, we found but few steady friends,
yet we had some good opportunities together;
several of the town`'s people also coming in.
I trust our visit was of service, and tended to edification,
and strengthening the two or three that dwell in that remote part of the world.
However, I thought I should not be easy without paying them a visit,
though I had to ride so far on purpose.

When I felt myself clear, I returned with my friends to the Wateree,
and was with them at their first-day meeting, and meeting for business.
We had good opportunities likewise in their several families,
which I thought would not easily be forgotten.
Then taking our leave of them in gospel love, in which we had paid them that visit,
we returned to Pedee, Samuel Millhouse still accompanying us.
The friends there, though their circumstances in the world were but low,
treated us very kindly.
Their love to truth, and diligence in attending meetings are worthy of notice;
for they had nearly one hundred miles to go to the monthly meeting they belonged to,
and I was informed, very seldom missed attending it.

Here my companion and I parted, he returning home, and I, with Francis Clark,
went towards Cane creek.
His company was so agreeable, that time did not seem long.
When night came we took up our lodgings in the woods,
and got next day to a place called Deep river,
there being several families newly settled there,
but they had not yet built a meetinghouse.
We had a meeting at a friend`'s house, and then proceeded to Cane creek,
where there is a large body of friends gathered there
in a few years from the several provinces.
They told me they had not been settled there above ten years,
but had found occasion to build five meetinghouses, and then wanted one or two or more.
I had good and seasonable opportunities among them,
being freely opened in the love of the gospel to declare the truth.

When I found myself easy to leave them, having had various meetings at Eno,
and several other places, which, for brevity sake, I forbear to mention; I,
with Jeremiah Pickett, then set out towards Virginia,
having nearly two hundred miles to travel, and had but one meeting in the way.
We got to Robert Langley`'s on first-day evening,
where I stayed to rest and refresh myself after so long and tedious a journey.
I then passed to Curies and travelled through Virginia,
having visited most of the meetings before, and came into Maryland.
I was at their yearly meeting held at West river.
It was very large,
and in the several sittings thereof overshadowed with the wing of divine power,
which tended to nourish the good part,
and to the gathering and settling the minds of many upon the sure foundation,
and kept down that spirit which would divide in Jacob, and scatter in Israel.

We parted on fourth-day in great love, some of us being nearly united in spirit.
For though many by baulking their testimony against that anti-Christian yoke of tithes,
and trading in negroes, have caused the way of truth to be evilly spoken of;
yet I was sensible that the regard of heaven was towards them,
and the merciful hand was still stretched out,
even towards the unfaithful and backsliders, that they might be gathered.
I had a travail and exercise upon my spirit for the cause of truth, and the great,
blessed and everlasting Name, which I, with many more, make a profession of,
might not be dishonoured; the faithful are indeed as stakes in Zion,
but they are but as one of a family, or two of a tribe.

I then took the meetings in my way to Pennsylvania, as Elk Ridge,
Patapsco and Patapsco Forest, Little Falls, Gunpowder, and so to Deer creek,
where our worthy friends John Churchman and his wife met me.
We crossed the river Susquehannah into Pennsylvania, and so to their house.
Having had many precious meetings in this journey,
and well cleared myself of those provinces, I was easy in my spirit,
and much comforted in the Lord, that he had been pleased thus far to help me through.
I tarried one night at John Churchman`'s, and next day, being the seventh of the week,
was at New Garden monthly meeting; on first-day at London Grove,
where there is a large gathering of friends.
It was a good opportunity, truth favouring us, we were comforted together in the Lord.
On second-day, the 29th of the fifth month, I got to Philadelphia,
having in this journey travelled upwards of two thousand eight hundred miles.
