== Chapter III

After my return from the southern provinces,
I stayed some weeks visiting meetings and some friends`' families in and about Philadelphia;
and was also in the Jerseys visiting several meetings,
and attended their quarterly meeting at Salem,
which held three days for worship and discipline.
It was an edifying time, things being conducted in a degree of the pure wisdom,
and the overshadowing of divine power was witnessed by many.
Then, having duly waited for the moving and putting forth of the good Shepherd, who said,
that "`when he puts forth his own sheep, he goes before them,`" I thought I felt a draft,
and not only so, but likewise true liberty, to visit New England,
which I had not done before.
If I had, I should have proceeded, in order to shorten my journey,
for it was against my own inclination to stay so long in and about one place.
Therefore I set out the 26th of the seventh month, Isaac Greenleafe accompanying me.

My first step was to Wrightstown,
where was held a general meeting for the county of Bucks.
Then we crossed the Delaware into New Jersey, and took meetings in our way to New York,
then to Flushing upon Long Island, and were at their monthly meeting.
Crossing the bay, we went to their quarterly meeting at Purchase,
and after this we took several meetings as they fell in our way to Rhode Island.
I had Robert Willis for my companion, a friend from the Jerseys,
who had drawings in his mind that way.
Many people came to our meetings in those parts,
who are not closely joined in outward fellowship with us;
yet were under the operation of the good Hand, and in degree convinced of our principles.
This, I thought, made our meetings more lively,
and the spring of the gospel to flow more plentifully,
to the watering of the thirsty ground.

When we had visited the meetings hereabouts, and taken our leave of friends,
we travelled through Connecticut government, having but one or two meetings in the way.
The Presbyterians, who, formerly in those parts,
were very rigid and bitter against friends, are now become more loving,
and treated us very kindly.
I had great drawings of the Father`'s love towards them,
believing his secret hand was at work to bring them
from the barren mountains of their lifeless profession,
to serve the living God in newness of life.
We came to Leicester, where there is a little handful that go under our name.

We had a meeting with them on first-day, the 20th of the eighth month,
and were refreshed together, being strengthened in the God of our salvation.
Then we had a meeting at Bolton, about thirty miles from there,
where we met with Samuel Spavold, in his return towards Pennsylvania,
he having visited most of the meetings in New England.
We had a good season together.
Saluting one another in that unity and fellowship which
brethren and fellow-labourers ought to dwell in,
we parted; and my companion and I went to Uxbridge, and had a meeting.
Then to Mendara, where we tarried all night at Moses Aldrige`'s,
and had a meeting next day; so on to Wainsockit, where we had a meeting.
The weather being very hot, many people were nigh fainting;
but praises be to the great Name, the meeting concluded well.

On first-day we were at Providence yearly meeting, which is only for worship.
It was very large, and tended to the gathering and staying people`'s minds on Christ,
the chief corner stone and Rock of ages; for truth had the dominion,
and the Lord`'s power was felt.
We had our outward entertainment at Stephen Hopkins`', then governor of Rhode Island.
He and his wife treated us with hearty kindness.
We had meetings at Cranston, Warwick, and East Greenwich, and upon Conanicut island.
We then crossed the river, and came to Newport,
and attended both their meetings on first-day, which were large;
a great number residing thereabouts, who go under our name.
But, with sorrow of heart may it be said,
in the time of ease and plenty many have taken their flight.

We left Newport on third-day, and had a meeting at Portsmouth,
in which we had good service for Truth.
Then crossing the bay, had a meeting at Freetown upon the main,
in which we were favoured with the openings of Truth, and left them in peace.
I took notice of a negro man who was with us at several meetings,
and by his own industry, with the help of some friends, had purchased his freedom,
that he might attend meetings; having, for some time,
been convinced of the blessed Truth, which he much prized, and told me,
as he had been obedient to the operation of it, which works by love,
he found himself engaged in his mind to exhort his fellow creatures
to come to the Divine principle in themselves;
that they, by yielding obedience, might know a being saved by it; or to that effect.
This I could not gainsay or discourage;
but desired him to be faithful to the manifestation of Truth in his own heart,
and the measure of grace he had received.
We parted in love and good will, being brethren of one Father.

Our next meeting was at Little Cranston,
after which I parted with several friends in the unity of the one Spirit,
which had brought us into nearness and fellowship with each other;
they returning to their places of abode, and I, with my companion,
and a young man who accompanied us several weeks, still kept forward.
I was enabled to labour through these parts beyond all outward expectation;
for though the meetings were large, by reason of a great coming in of other people,
I found that gracious promise fulfilled; "`As the day is, so shall your strength be.`"
We were at Accoakeset, Newtown, and Dartmouth or Aponiganset,
and had a meeting at each place.
The last meeting, I thought, did not consist of less than eight hundred people.
At Acushnett, Rochester, Taunton, and Freetown,
we had many living and good opportunities to declare
Truth in the free extendings of gospel love;
also at Swansey on a first-day, had a satisfactory opportunity.
While we were visiting those places, we took up our quarters at Paul Osbourn`'s,
who often accompanied us from one meeting to another,
his heart being free and open towards his friends, and to serve Truth.

Having well cleared ourselves, we went towards the yearly meetings at Boston, Lynn,
and Salem, the 22nd of the ninth month.
They began at Boston.
I do not remember that I had seen so much stillness and gravity in so great an assembly,
as I observed there.
It consisted of people of different persuasions.
We have great cause to bow in humble thankfulness to the God of all our mercies,
that he has been pleased to make way for his people to enjoy
their religious meetings without the least molestation,
in this and many other places,
where our worthy friends formerly suffered sore persecution, by long imprisonment,
grievous whippings, spoiling of goods,
and some of them laid down their lives for the testimony of a good conscience.
And though our God be a gracious, merciful, and long-suffering God,
yet he will take vengeance on all the workers of iniquity,
and the day of his wrath will break forth like a consuming fire,
in a time when it is not looked for.
As he said, so he will do; "`For,`" said he, "`I am a jealous God,
visiting the sins of the father upon the children,
unto the third and fourth generation of them that hate me;
and showing mercy unto thousands of them that love me, and keep my commandments.`"
So it is plain the Lord is equal in all his ways; for,
concerning those that are the offspring of that hard-hearted,
wicked and perverse generation,
that persecuted and shed the blood of the innocent servants of the Lord,
if they but turn to him with their whole hearts, so as to love him,
and keep his commandments, they will surely find mercy;
but if they continue in a state of rebellion and hardness of heart,
and sin against his light and good spirit in their hearts, as did their forefathers,
he will visit them with his judgments for their iniquities;
and for the sins which they and their forefathers have committed,
he will pour forth the cup of his indignation without mixture.

After those yearly meetings, we, with several friends,
went towards the yearly meeting at Dover, and Cachecy,
taking several meetings in the way, as at Ipswich, where no friends lived;
but we got leave to have a meeting in their courthouse.
It was disturbed by a man standing up when I was in testimony,
who said that I struck at the foundation of their principles.
He was a very hot man, and held the doctrine of absolute predestination.
I told him, Truth struck at the unsound foundation; but as he was in heat and anger,
not fit to dispute about religious matters, he sat down,
and a woman sharply reproved him for his rude behaviour,
she being grieved that the meeting should be disturbed; for it was in a good frame.
Several of the people.
I believe, were ashamed of his conduct.
After a little silence, a friend stood up, and had a good opportunity.
Then I had to clear myself of what was upon my mind,
and the people being still and attentive, the meeting concluded well.
The man who had opposed me shrunk away, and I saw him no more, though I looked for him,
and in coolness thought to have a little further discourse with him.
That night we went to Newberry, where we had a meeting,
much to my comfort and satisfaction.
We had meetings also at Amesbury, Hampton, and Dover.
Friends had been sorely wounded and scattered in their minds in these parts,
by an unstable spirit.
Those yearly gatherings were large, and I hope tended to the honour of Truth.
We went next to Berwick, and had several meetings there;
and travelled through the woods to Casco, where we had an opportunity with friends,
and such as attend their meetings.

We crossed the bay to Small Point,
and in our return had a meeting upon a neck of land called Meryconeague.
The meeting at Small Point was the northernmost settlement of friends upon the continent.
We returned by Boston, having several meetings in our way; and from there to Pembroke,
Sandwich, Yarmouth upon Cape Cod, Suckanessit, Wood`'s Hole,
and from there took passage to Nantucket.
We stayed upon that island about a week, visiting friends in their families,
and had several public meetings with them.
It was an exercising time to me,
finding the true seed or life of religion suffering much,
by reason of strife and divisions.
I left them sorrowful, because I thought the root of bitterness was not removed,
though I was comforted in several meetings among
them with the shedding abroad of divine favour,
which strengthened me in the discharge of my duty;
and indeed there is a living remnant still among them,
which I charitably hoped would be preserved in the
innocency and simplicity of the unchangeable Truth.

Several Indians were there, natives of the island.
I had a desire to have a meeting among them, and acquainted them with it,
which they freely consented to; and at the time appointed,
their priest was waiting for us with his meetinghouse doors open,
and said he would have me go up into the place where he used to preach.
I told him, I chose to sit below with my friends.
I had a living, open time among them,
to set forth the necessity there was for them to turn their
minds to the grace of God in their own hearts,
a measure whereof they, as well as others,
had received according to the apostle`'s doctrine; which, if they gave good heed unto,
and yielded obedience to the manifestation thereof, would bring salvation.
The meeting ended in prayer and praises to Almighty God,
for his great mercy and lovingkindness to mankind,
in sending his Son to be a light to enlighten the Gentiles,
and for his salvation to the ends of the earth.
Solidity appeared in their countenances,
and they behaved with sobriety very becoming the occasion of our assembling together.
I should be glad there was more of it to be seen among those that profess Christianity.

We parted with them in the love of the gospel, which I felt in my heart towards them.
The wind coming fair, we took our leave of friends and went on board a vessel,
a friend named William Hussey being master.
In the evening of the same day we landed upon an island called Martha`'s Vineyard.
We quartered at a man`'s house that called himself by our name,
and I thought he had some zeal for Truth, and the promotion of it;
for after he understood we had a desire to have a meeting,
he hastened and called in his neighbours, and a solid, good time we had together.

The next morning, being favoured with a fair wind, we crossed the Sound to Dartmouth,
and landed nigh the meetinghouse, where we met with several friends,
who had attended the quarterly meeting.
The meeting ended that day; we had a confirming, sweet opportunity together,
in waiting upon the Lord, before we parted with them and those that came from Nantucket.
Next day we got to Freetown,
and in the evening had a good opportunity at the house of Abraham Barker,
with the friends that lived thereabouts.
To this meeting came the negro man I mentioned before.
He told me he had been visiting some of his own colour, and was returning to Newport,
where he lived; but in his way, he said, he thought he must go by Abraham Barker`'s,
though out of his way, not knowing we were come from Nantucket.
When he saw us, he seemed to be almost overcome with joy, and was of service to us;
for we wanted to send somebody over the bay, either that night, or early next morning,
to appoint a meeting for us at Portsmouth upon the island;
and none readier and more willing than poor Caesar;
for he was stirring so soon in the morning,
that he gave full notice up and down the island.
So we had a large gathering collected in due time,
though the time to give notice in was short, and seasonable advice was handed forth.
From there we went to Newport with our friend Thomas Richardson,
with whom we had lodged when there before, and were at their monthly meeting;
we stayed with them also on first-day.
Our meetings were richly favoured with the free extendings of divine power and wisdom;
so that I was truly thankful I had been helped to get through the various
difficult paths I had to tread in this unstable part of the world.

On second-day we left Newport, and crossed the river to Conanicut island,
where a meeting was appointed for us; wherein we were well refreshed together,
and the conclusion was in prayer and supplication for each other`'s growth, preservation,
and establishment in the blessed Truth.
We here parted with some friends of Rhode Island, under a sense of divine favour,
and in the uniting love of the gospel, which had caused us to be near one unto another.
Then crossing the river upon the main land, we had meetings at Kingwood, Perry`'s,
Richmond, and Hopkinton, and so passed through Narraganset, till we came to Westerly,
the last meeting in those parts we had to visit.
We took our leave of those friends that accompanied us in great good will;
then travelled through the lower part of Connecticut government, crossing many rivers,
and the weather extremely cold.
It was hard for me to bear; but praises be to the great Name, I was preserved in health,
and my natural strength did not at all fail.

When we had travelled hard about three days, we came again among friends;
and on sixth-day had a meeting at Inomarance.
It was to me a good time; for the bread that refreshes the hungry soul was broken.
We then crossed over to Long island, and were at the meeting at Flushing on first-day,
the 20th of the eleventh month.
On third-day we had a meeting at Cowneck, and on fourth-day at Westbury.
Lukewarmness and indifference much prevailed in many places among the professors of Truth.
I had often to bear my testimony for the blessed Truth against earthly mindedness,
and all the deceitful and false coverings of the flesh, which had been the cause of it.
I returned back to Flushing in order to be at their quarterly meeting,
which began on seventh-day, for ministers and elders.
It was attended with a degree of divine favour, to the comforting of our souls.
Those meetings were measurably blessed with the presence
of the great and good Master of our assemblies,
and his voice was heard by some, to speak as never man spoke;
and we had to conclude in humble supplication to him for his help,
and the continuation of his mercy,
in visiting and turning the hearts of his people to himself.
I then visited the meetings upon the island, which I had not yet been at,
and had meetings at Rockaway, and again at Westbury monthly meeting,
where I was closely exercised on Truth`'s account;
but was helped to clear myself of what lay upon my mind, and came away easy.

I then went to Bethpage, and had meetings also at Sickatauge and Oyster bay,
where there had been a large meeting, but it was much declined;
yet we had a large meeting, accompanied with divine power, to my great comfort.
On first-day I was at Jericho.
The meeting consisted of several hundreds of people,
who heard the Truth declared with great attention, the power of it being over all,
to the praise of Israel`'s God.
Passing through New York, I stayed their meeting;
then crossed over by way of Staten Island, to Rahway in East Jersey,
where I had a meeting with friends, and some others that came in,
to the edification and comfort of several, myself in particular;
being therein strengthened and encouraged to go forward
in the future service I might be engaged in.
We lodged at Joseph Shotwell`'s, and on sixth-day had a meeting at Plainfield.
It was small, by reason of short notice,
yet favoured with the overshadowing of divine favour;
for which our souls were bowed to the Father of all our mercies.

I rode to Whitpiny on seventh-day to the quarterly meeting, which began on first-day.
It was a good, satisfactory time.
I stayed there on second-day, and was at the preparative meeting, which was satisfactory,
several things being opened and delivered in the pure wisdom,
concerning the things of God, and the good order established in his church.
I had some good, seasonable opportunities in some friends`' families;
and on third-day had a meeting at Rahway, appointed for those of other societies;
which was to good satisfaction.
On fourth-day we went to the Great Meadows,
where we had a meeting with the friends there, among whom is a living remnant.
We were made to rejoice together in a true sense
of the shedding abroad of divine love in our hearts.
On fifth-day I went to Kingwood monthly meeting.
I had some service there for Truth,
in recommending to the good order of the gospel in each branch of our Christian discipline;
which I observed to be much lacking among them.

On sixth-day I had a meeting at Amwell, at the house of Gershom Mott.
It was an open time, Truth in a good degree prevailing.
On first-day had a meeting at Crosswicks; a close, searching time it was,
many states being opened in the love of the gospel.
On second-day I was at a meeting at Freehold,
in which I was largely opened in the free extendings of divine favour.
On third-day, the 19th of the twelfth month, I had a meeting at Upper Springfield.
I was led to speak to the states of the people in a close manner,
and the meeting ended well.
On fourth-day I had a meeting at Old Springfield.
It was an edifying and good meeting.
Truth having the dominion, to the praise of Israel`'s God.
On fifth-day I went to Little Egg Harbour, and had a meeting there next day,
in which I was enabled to clear myself in a good degree, and came away easy.

We crossed the river in the evening to Great Egg Harbour.
The weather being very cold, and having much ice,
our journey was attended with some difficulty; but we got well over the river,
though in the night, to Great Egg Harbour, and lodged at Robert Smith`'s,
an ancient friend, who, with his wife, entertained us very kindly.
We had a meeting there on seventh-day, held at a friend`'s house,
by reason of the extreme cold season.
We had a solemn, comfortable time together, and after meeting,
rode to the other meeting along the bay shore, towards Cape May, which was on first-day,
the 24th of the twelfth month, 1758.
It was a close, exercising time with me.
The frost was so sharp, we could not cross the bay to Cape May,
but were obliged to ride round to a bridge, where we crossed the river;
which was about forty miles out of the way, and being strangers to the road,
we met with much difficulty through the woods,
and there was no beaten path to be seen for some miles.
I saw that the friend who pretended to be our guide, was going wrong, and told him,
if we took that course, it would lead us much out of the way; for I was very uneasy.
Upon which he took out his compass, and finding it so,
altered his course to that which I thought lay towards the road.
I then found my mind quite easy, and said, I thought we should soon find it,
which so happened.
I said not much to the friends, but was thankful to the Lord,
to find he was pleased to draw my mind towards the way we needed to go.

Night coming on with much rain, we lodged at a tavern,
and next morning got to William Townsend`'s,
where we had two meetings to pretty good satisfaction.
On seventh-day we rode about forty miles to John Reeves`', at Greenwich,
were at the meeting on first-day, the 31st of the twelfth month,
and had good service for Truth.
In that place there is a promising appearance among the youth, of the prosperity of Truth.
Second-day, the 1st of the first month, we had a meeting at Alloway`'s creek,
which was attended with good; I being helped beyond my expectation.
On third-day I had a meeting at the head of Alloway`'s creek,
where I was led to speak to several states in a close manner,
and came away much refreshed in the Lord; praises be to his great Name forevermore.
I had a meeting at Salem on fourth-day, there being a marriage,
and the new wine was handed forth,
which made several rejoice under a sense of divine favour communicated to our souls.
On fifth-day I had a meeting at Pilesgrove.
It was large, several of other societies being there;
I was opened in the free extendings of gospel love to their souls.
It was a good time to many, magnified be the God of our salvation.
On sixth-day I had a meeting at Woodbury, which was a solid, good time.

The 6th of the first month I went to Haddonfield, and lodged at the widow Eastaugh`'s,
where I was very kindly entertained.
On first-day I went to Evesham meeting, where I had been before,
and had service for Truth in the love of the gospel.
Haddonfield monthly meeting being on second-day, I stayed there,
and had an exercise on my mind for the honour, promotion,
and prosperity of the blessed Truth, and that all might act in the wisdom,
power and life of it, and might know self kept down by the power.
I rejoiced that I was at this meeting,
Truth favouring and the Lord`'s power being over all.
I was made thankful in my heart to the great Author from whom all our blessings flow.

I went to Philadelphia on third-day,
but finding my mind drawn towards the eastern shore of Maryland,
I set out again on fifth-day, the 11th of the first month,
and reached Wilmington that night.
I lodged at William Shipley`'s when at Wilmington, and having seen his wife Elizabeth,
when in old England, in the service of Truth,
the remembrance of which had often been revived upon my mind,
believing her to be a mother in Israel,
and a sanctified vessel fitted for the Master`'s use,
I could not but rejoice to see her again, and find her alive in the Truth,
now in her declining years.
Our next meeting was at the head of Sassafras.
It was a hard time with me in the forepart of the meeting;
yet I came away well satisfied, Truth favouring towards the conclusion,
to the honour and praise of Israel`'s God.
After meeting I went home with Joshua Vansant, where I lodged.

The next morning was at Cecil.
I was exceedingly poor and low, and deeply exercised in my mind, but was helped over all,
and beyond all thought and expectation of my own; for I think I may say in sincerity,
I had no trust or confidence, save in the Lord alone, who hitherto has been my rock,
and my strong tower, my sure helper in every needful time.
May I, with all mine, put our trust in him,
has often been the earnest prayer and supplication of my soul.
I had a meeting at Queen Ann`'s, which ended well, the Lord`'s power being felt among us,
to our comfort: I lodged at +++_______+++ Furner`'s, where we had a meeting with the family,
and several others who came in.
I hoped it might tend, in some degree, to stir up the careless, and warn the unfaithful.
The 21st of the first month I had a meeting at Tuckahoe.
It was small, but attended with good, the Lord favouring us with his presence,
according to his gracious promise.

On first-day I crossed Choptank river over to Marshy creek, and was at their meeting.
I was much comforted, and had peace in the discharge of what I believed to be my duty;
though I travelled in great fear and much weakness at times.
I was at Choptank meeting on second-day, which was silent; yet I came away easy,
with sweetness upon my mind, having been strengthened in my silent waiting.
I had a meeting on third-day at Third-haven,
where I was sensibly affected with the states of those who were
not willing to take up the cross to their corrupt wills and inclinations;
and had to bear testimony against unfaithfulness, disobedience, truth-breakers,
and such as brought dishonour upon the truth and our holy profession.
I felt the love of the gospel flow freely, even towards the backsliders;
and in it warning them, I came away sweetly comforted in my spirit.

Fourth-day I went to the Bay side, where we had a meeting on fifth-day,
with a few lukewarm professors.
I had to exhort them to more diligence in keeping up their meetings, and waiting therein,
that they might know the renewing of strength in the Lord, and be enabled to worship him,
as he is a spirit, in spirit and in truth.
On seventh-day I was at the quarterly meeting of ministers and elders at Third-haven,
where I had some service for Truth.
On first-day I was again at Tuckahoe meeting: Truth favouring, in the love of the gospel,
many divine truths were opened to the edification and comfort of our souls;
and it ended in humble supplication and prayer to Almighty God for his help, strength,
and preservation in the way of truth and righteousness.

On third-day I was at Third-haven, at the quarterly meeting,
where several friends had good service for the truth,
in the love of which we were comforted together in the Lord,
and helped to bear testimony against those things which are crept
in by reason of unfaithfulness among the professors of truth.
On fourth-day, the 31st of the first month, I went with several friends towards Lewistown.
On sixth-day had a meeting at Cold Spring,
where is a poor company of indifferent lukewarm professors.
On seventh-day I had a meeting at Motherkill, which was pretty large,
and attended with the shedding abroad of divine love to the people.

I was at Little creek on first-day, where we were comforted together in the Lord.
Here is a promising prospect among the young people of the prosperity of truth.
I was at Duck creek meeting on second-day, which was small,
yet a living open time to several.
From there I passed to George`'s creek, where I had a meeting; and so to Wilmington,
where I met with Samuel Spavold, who embarked for England on fifth-day,
the 8th of the second month, 1759.
I stayed the monthly meeting, which was that day,
in which I was largely opened to the states of several, things being much out of order,
by reason of a difference which had happened among them.
I came away, I thought, clear and easy in my mind.
On seventh-day, the 10th of the second month,
I was at Concord quarterly meeting for ministers and elders, which was solid,
and much good advice was handed forth.
On first-day I was at Kennet, and had large openings to the people,
in the free extendings of divine love.
On second-day was again at Concord quarterly meeting for worship and discipline,
in which Truth`'s testimony went forth against disorderly gainsayers and libertine spirits.
I had a word of comfort and consolation also to the weak, feeble mourners in Zion.
Things closed well, and we parted refreshed in the Lord.
On third-day I was at a meeting at Providence, held for young people chiefly;
it was to good satisfaction, and ended well.
On fourth-day, the 14th of the second month, I had a meeting at Birmingham.
I felt the Lord with us, helping and making way by his own power;
praises be to his great Name forever!

After meeting, we crossed the river called Brandywine,
and went to my kind friend William Harvey`'s, where I was kindly entertained.
On fifth-day, the 15th of the second month, I had a meeting at Centre,
in Newcastle county.
I was glad and thankful in my mind,
to feel myself fully given up to what the good hand was pleased to give forth,
either to speak, or be silent.
On sixth-day I had a meeting at Hockesson, which was pretty large,
and in degree favoured; yet could not say I rejoiced,
for in that place I felt that the Seed suffered, as well as in many other places,
where my lot has been cast of late; especially among the elders,
and those that should be the foremost rank in religion.
I could not help mourning in secret, at times,
under a sense of the relapsed state of the church of Christ in many places.
How departed from the innocency and simplicity,
and decking herself with her own ornaments of self-righteousness,
and also stained and spotted with the world, and the filth of the flesh!

On seventh-day I was at the meeting for ministers and elders,
held at London-grove for that quarter, and also at their meeting on first-day,
which was blessed with the company of Him that dwelt in the bush;
for his sacred fire was kindled in our hearts, with living desires,
that the mount of Esau might be consumed.
On second-day, after a solemn humbling season together, in true spiritual worship,
which ended with thankfulness and living praises to Almighty God,
the affairs of the church were carried on, and transacted in brotherly love,
and condescension towards one another.
We had also a comfortable and confirming time together on third-day,
at our farewell meeting,
which being a fresh seal of the Father`'s love and
continued regard for his church and people,
in uniting and making us to rejoice together in him, will remain, I hope,
upon many minds, with gratitude to the great Giver of every good gift.

While I was here I lodged one night at John Smith`'s, an ancient friend,
who had kept his place well in the truth, and also at Joshua Pusey`'s,
a good solid friend, who had a hopeful offspring.
From here I went to West Cain, and lodged at George Singular`'s,
and was at the meeting on fourth-day, the 21st of the second month.
It was an exercising time with me,
yet I could not say but I thought truth had the dominion.
After meeting I crossed the Brandywine, and went to East Cain,
and was at the meeting on first-day, the 22nd of the second month,
which proved a helpful edifying season to many.
I went after meeting to Downing`'s town, and had an evening meeting at a friend`'s house,
which was thought by some to good service.
On sixth-day I had a meeting at Nantmill, after which I felt easy in my spirit,
notwithstanding I had close and hard labour.
On seventh-day I had a meeting at Pikeland, which was a watering time,
for the Lord has a living seed in that place,
which in his own time he will raise up to the praise of his own great Name!

On first-day I was at Uwchland meeting.
It was large, and attended with a good degree of divine favour,
which made it satisfactory to many, though not so open to me as at some other times.
Our next was at the Forrest,
or Robinson`'s. I was much exercised to recommend to an inward waiting,
which by many professors is much neglected.
Our next meeting was at Exeter.
On fifth-day we had a meeting at Reading, and afterward went to Maiden creek.
At Reading our meeting was in the town-house, or courthouse,
where several soldiers came and many of the town`'s people, who behaved very soberly;
the good power of truth coming over all, and prevailing,
many minds were humbled and brought low.
It was a good time, especially to some of the soldiers,
who were reached by the invisible power of Truth.
The meeting ended in praises and thankfulness to the Almighty,
for his unspeakable favours; who is over all, worthy forevermore!

After meeting we went to Maiden creek, where we had a meeting on sixth-day.
It was large, and to tolerably good satisfaction.
We lodged at Moses Star`'s. On first-day we had a meeting at the Great Swamp.
It was a living satisfactory time to several; and, in general, an edifying season.
I dined, after meeting, at Morris Morris`'s, the husband of the worthy Susanna Morris,
and then rode to Plumstead, where we had a meeting on second-day,
the 5th of the third month.
The good power of Truth was also felt among us in this meeting,
to the edification and comfort of our souls.
On third-day I was at Buckingham monthly meeting,
in which I was favoured with the pure life and fresh spring of the gospel,
which ran freely in the love of it.

Here is a large body of people in this province of Pennsylvania,
the elders of which are too much in the outward court,
which is only trodden by the gentiles, or such as are in the spirit of the world;
yet a young and rising generation is here,
as well as in several other places where my lot has been cast,
since I came into this land,
whom the Lord has visited by his power and good spirit in their hearts, which,
as they take good heed in yielding obedience to,
and bring all things into the obedience of Christ,
will crucify all their inordinate desires, evil thoughts and imaginations,
and enable them to bring forth the fruits of the spirit, which are love, joy, peace,
gentleness, meekness, long-suffering and goodness; against these there is no law.

I have often travailed for them since I have been among them, lest the labours of love,
which have long been bestowed on you,
O America! you favoured of the Lord! should be bestowed in vain;
and instead of bringing forth fruits to the praise of the great Husbandman,
you should bring forth wild grapes, fruits of the flesh,
such as he can in no way take delight in; and instead of a blessing, draw down a curse,
and provoke him to take away the hedge of his protection,
and you be trodden down and laid waste by the devourer; and for your ingratitude,
disobedience and unfaithfulness to him; yes,
lest he should even command his clouds not to rain upon you any more.
May you never harden your heart and stiffen your neck against so tender a Father,
who has so long nursed and fed you; so merciful a God,
who has often pardoned your iniquities, though they have been as a thick cloud.
He has so visited you, in mercy sparing you, and waiting for your return,
that if you return not with your whole heart,
his anger and indignation certainly will break forth against you,
so as not to be quenched; no, though you may make many prayers,
and spread forth your hands, he will not hear nor regard;
inasmuch as you have hated instruction, and did not choose the fear of the Lord,
but have set at naught all his counsel, and would not take heed to,
nor regard the secret reproofs of instruction in your own heart.
He will also laugh at your calamity, and even mock when your fear comes;
when your desolation is unavoidable, and your destruction as swift as the whirlwind.
I humbly beg this may never be your doom;
but in order that the days of his mercy and your tranquillity may be lengthened out,
let truth take place, that equity, justice, and true judgment,
may run down in your streets like a mighty stream; then shall your peace be as a river,
or as the waves of the sea, that never can be dried up.

I was at Wrightstown on fourth-day; it was an exercising and low time with me,
but I trust truth did not suffer on my account.
On fifth-day I was at Makefield.
It was a living and precious time in the meeting,
Truth`'s power prevailing to the dividing of the word aright;
the sense of which is cause of true thankfulness to the humble-hearted.
I had a meeting at the Falls on sixth-day, to solid satisfaction;
and afterwards rode to Bristol, and had a meeting on seventh-day,
the 10th of the third month.
I was glad Truth in some good degree had the dominion.
I stayed the meeting on first-day, the 11th of the third month.
This was a good time to us; the Lord`'s power was over all,
to the praise of his own great Name!

On second-day I had a meeting at Abington,
in which I was favoured with the openings of truth in the spring of the gospel,
exhorting all to faithfulness, even the rebellious and gainsayers;
that they might come to know salvation to their souls through Christ.
My next meeting was at Horsham, which was large; in which Truth favouring,
it was made a precious time to many, as I then felt.
On fourth-day I had a meeting at Gwynedd or North Wales,
where there is a pretty large body of friends; the sight of whom, in many places,
and the sense of divine favour still extended towards them,
was cause of humble thankfulness.
On fifth-day, the 15th of the third month, I got to Philadelphia,
having in this visit been absent from there about nine weeks.
I made my home, while there, with the widow Rachel Pemberton and her son John,
worthy friends; she a mother in Israel,
and a great caretaker of the poor servants who have been sent,
not only in opening the door and kindling the fire,
but in ministering everything that she thought might
be a help and service to them in their journey;
for which, I am fully persuaded in my mind, she, with many others,
will not lose their reward.
"`Inasmuch as you did it unto one of those little ones,`" says our dear Lord,
"`that believe in my name, you did it unto me.`"

The 31st of the third month I left Philadelphia again,
in order to visit a few meetings in Chester county, which I had not yet been at.
On first-day I was at Providence meeting, which was a good and satisfactory opportunity,
the state of things was much opened, and our minds in a good degree humbled,
under a lively sense of divine favour.
I was at Concord on second-day.
John Churchman also being there, was very helpful to settle the minds of some,
who had gone into jangling about some things which had happened among them.
This being their monthly meeting,
we left them to appearance in a pretty quiet frame of mind, and things ended well.
After meeting I rode towards Haverford, and on third-day was at that meeting,
which was well.
On fourth-day I was at Darby meeting.
It was an exercising time to me, things being much out of order,
some differing in their judgment concerning what was, and what was not,
consistent with our religious principles in regard to military service,
in which several who go under our name, had been meddling and concerning themselves.
This brought great exercise and trouble on the faithful.
A grievous refractory libertine spirit I saw appeared;
yet it was in a good degree kept down, and truth, in some measure had the dominion.

On fifth-day, the 5th of the fourth month, I was at Springfield.
It was a large, good, seasonable opportunity to many.
On sixth-day I was at Newtown meeting; in which Truth`'s way was largely opened,
and livingly set forth in the power of it,
to the humbling and solid satisfaction of many: a day to be remembered by the sensible.
After meeting I went to George Miller`'s, where I had been before; a very kind friend.
On first-day I was at Middletown meeting.
It was a large gathering, and Truth had the dominion over all;
though many dry professors were listening and longing after words,
which sometimes causes the living stream to be withheld for a season;
yet the great goodness and condescension of a merciful God is wonderful,
in that he is pleased to cause the living stream of the gospel
ministry to issue and break forth in a wonderful manner,
to the refreshing of his own heritage.
The glory and honour, with living praises, be given to him, and that forevermore!

I had an evening meeting at the schoolhouse;
it also was an opportunity of good to our souls,
which were refreshed together in the Lord.
Isaac Greenleaf, of Philadelphia, being with me, on second-day,
we were at Goshen meeting, which was attended with good; truth in some degree favouring.
We lodged at Aaron Ashbridge`'s, and on third-day had a meeting at Bradford.
We were much hindered in our way by the waters being raised,
and a friend was in great danger of being carried away, but was preserved.
We got to meeting, though friends had been gathered an hour or more.
It proved a good season; the Lord had compassion on us,
and caused his gospel rain to descend on the thirsty ground,
to the refreshing of that which was of his own right hand planting,
and also to the placing judgment upon the unrighteous part, and all the fruits thereof.
I came away thankful in my spirit to the Lord, for his great goodness to his poor people;
because I saw his mercy and lovingkindness endure forever.

On fourth-day we had a meeting at the Great Valley,
in which I perceived the extendings of good were offered,
even to the gainsayers and rebellious: a mercy unspeakable!
After meeting we went to a friend`'s house, with whom Margaret Ellis abides,
and were at Radnor meeting on fifth-day, the 12th of the fourth month; in which,
though I was attended with much weakness, I thought I had some service for Truth.
On sixth-day I had a meeting at Merion, which was not an unprofitable season, I trust,
to several.
I returned that day to Philadelphia, and on seventh-day, with John Pemberton,
I rode to Plymouth, and was at that meeting.
On first and second-days, at New Providence.
On third-day returned again to Philadelphia, with some degree of satisfaction,
and attended their week-day meeting, there being a marriage.
Several rejoiced under a renewed sense of the ancient power
and lovingkindness of our heavenly Father`'s tender regard,
in that he was pleased to cause his love and life-giving presence to be felt among us,
to the refreshing of the sincere and upright-hearted.
Glory and praise be to his great Name; for he is worthy forever!

I stayed in and about Philadelphia between three and four weeks,
in which time I attended meetings as they came in course,
and also paid several religious visits to families,
as I found my mind drawn in the movings of Truth; in all which service,
though but small in comparison of some others, I found my spirit favoured with sweetness,
and a degree of peace.
While I waited here, supposing my service to be mostly over upon the continent,
having paid a general visit, I unexpectedly, and pretty suddenly,
felt a strong draught towards Barbados, or the West India islands.
I acquainted friends therewith, and made some essay for a passage,
yet saw not my way quite clear; but in waiting felt my way open towards the Jerseys,
and on the 12th of the fifth month, went with John Pemberton to Mount Holly,
and was at the two weeks`' meeting on first-day; and on second-day at Moorstown,
where a meeting was appointed for two friends,
who were on their way towards Salem yearly meeting, where I was also with them.
On third-day John Pemberton left me at Ancocas,
which meeting was in a good degree satisfactory, and also to the honour of truth,
the edification of the Lord`'s people, and the praise of his great name!
On third-day evening I came to my worthy and well esteemed friend Elizabeth Eastaugh`'s,
where I lodged.
On fourth-day I was at a meeting at Haddonfield; on fifth-day at Woodbury;
sixth-day at Solomon Lippincott`'s; and seventh-day at Pilesgrove.
All these meetings, I thought, had a good tendency to the edification of the churches,
and ended well.
Thanksgiving and praise be to Him who lives and abides forevermore!
