== Chapter IV

The 19th of the fifth month, 1759, the yearly meeting for worship at Salem began,
where we were much comforted together, in the enjoyment of divine goodness.
The free extendings of the gospel spring flowed plentifully,
to the watering the heritage of God; the sense whereof bowed many with humble reverence,
in praises to his great and everlasting name, who is worthy forever!
The 25th we had a meeting at Evesham, and went next day to Mount Holly,
where also we had a meeting; on seventh-day to Crosswicks,
where their quarterly meeting began for ministers and elders.
On first-day I was at Bordentown in the forepart of the day,
and at Trenton in the evening; at which meetings we were measurably comforted.
On second-day I was at Crosswicks again, at the meetings for worship and discipline,
wherein truth favoured us in a good degree.
On third-day the meeting was very large,
and I was deeply engaged for the honour of Truth`'s cause,
there being a loose libertine spirit among some who go under the name of friends,
yet never came under the yoke of Christ, to know the deeds of the body to be mortified;
but live at ease in the gratification of their hearts`' lusts,
and cause the way of Truth to be evilly spoken of.
My concern was chiefly to such as live at ease in Zion, and to the backsliders in Israel,
yet I had a word of comfort to the mourners in Zion and the heavy-hearted in Jerusalem,
that they might hold on their way.
I was glad of so seasonable an opportunity,
wherein I was led to speak closely to the states of many, in true gospel love,
which was as a seal of divine favour.

Upon our taking leave, we committed one another to the Lord,
and parted in great love and true gospel fellowship.
I then crossed the Delaware at the falls,
in order to see my friends once more in Bucks county, where there is a large body,
and got to my worthy friend John Scarborough`'s, on fourth-day,
with whom I had travelled several weeks, both in the Jerseys and Maryland.
I had great satisfaction in his company, he being a man of a good understanding,
a tender spirit, and very serviceable in the church.

The quarterly meeting for ministers and elders began at Buckingham on fourth-day,
the 30th of the fifth month, which I attended,
and also on fifth-day a meeting for worship and discipline,
and I thought different sentiments were getting in among them.
If great care is not taken to keep to Truth`'s teachings,
and the unerring guidance of it, which will subdue and keep down all unruly spirits,
there will be great trouble and uneasiness, if not a separation, in many places;
for I saw an evil spirit of dissension was got into the church,
and in the ways of its workings, it appeared in diverse shapes,
in order to draw after it the hearts of the simple, and such as, like itself,
are unstable; for it is an unstable spirit, and by this it may be known,
and such as are led into its ways and own its workings.
For they will be restless, not easy, under the cross;
and will cast off the yoke of Christ, and go from his teachings, meekness and humility,
into a haughty, proud spirit, which is rough, full of hatred and envy, despises counsel,
and will not bear reproof.
This spirit, I thought, I perceived working in the mystery of iniquity;
but its time is not yet fully come to bring forth its monstrous birth.
The Lord`'s mercy is very great to his people,
for this seed of the serpent has hitherto been crushed and put by, in its puttings forth;
and the true seed, though through hard labour and travail,
has been brought forth into dominion, to the praise of Israel`'s God.

This quarterly meeting consisted of several hundreds, mostly a young generation.
The gracious extendings of divine goodness were felt,
and Truth`'s power prevailed over all the powers and spirits of darkness.
I was glad I was here, and my spirit rejoiced in the Lord, the God of my salvation.
After meeting on sixth-day, I went home with Samuel Wilson.
On first-day I was at Plumstead meeting, which was attended with good,
the power of Truth prevailing.
In the evening I was at a meeting near Buckingham, at a school-house.
It was a large gathering, and we were much comforted and refreshed together in the Lord.
I was at their monthly meeting at Buckingham on second-day, the 4th of the sixth month,
in which, through the prevalence and owning of Truth,
which came over the minds of the people, things were carried on well,
both in the time of divine worship and in transacting the affairs of the church;
for the power of Truth kept down all restless and unruly spirits,
which at times are putting up their heads in opposition to the testimony thereof,
and are for trampling all discipline under foot.
I was deeply exercised in my spirit before the Lord at times,
that I might be kept in the innocency, meekness, and pure wisdom.
Some being, as I thought, righteous overmuch,
I was afraid lest they should destroy themselves, and so dishonour the cause of Truth,
which they at times had so zealously contended for.

After this meeting was over, I went to Wrightstown monthly meeting, which was next day.
In this meeting I had hard labour and exercise; yet things ended well,
and I came away satisfied and thankful in my heart to the Lord,
for his unspeakable mercies.
The Falls monthly meeting being on fourth-day, I was there also,
had some service for Truth, and parted with several friends in much love and tenderness,
we not expecting to see each other again in mutability.
On fifth-day I was at Middletown monthly meeting,
in which I was drawn forth in the living spring of the gospel,
both in the men`'s and women`'s meeting.
Then feeling my spirit easy and clear,
I left them in love and the unity of the one spirit,
which had united us together in a near manner.

On first-day I was again at North Wales, and had good satisfaction at their two meetings.
On second-day I returned again to Philadelphia, having been about a month from the town.
On third-day, the 12th of the sixth month, I was at the Bank meeting,
in which we were comforted together, it being an edifying season to many.
I stayed in and near Philadelphia about four weeks,
visiting some families and attending meetings as they came in course,
though in meetings I had little to say,
being shut up and much bound in my spirit to keep silence in that city.
The cause is best known to the great Overseer of his people,
who can do with them as seems to him good:
and I saw it was good for his servants to be resigned and
contented with all the openings and shuttings of his hand;
with the various dispensations he is pleased to lead through,
that there may not be any confusion throughout the camp of God`'s Israel.
I could not but rejoice in thankfulness of heart,
that I was quite silent and still in my spirit;
being made sensible it was the Lord`'s own doings,
and indeed it is marvellous in our eyes, that he who is the Captain of our salvation,
should call for such a cessation of arms for a season,
that his soldiers may take a little rest in his royal
pavilion and under the canopy of pure love.

I was at Darby week-day meeting the fourth of the week;
on fifth-day at Chester weekday meeting; and on sixth-day at Chichester,
where a meeting was appointed for me; which was large,
and accompanied with the free extendings of divine mercy to our souls`' refreshment.
On seventh-day I was at London-grove monthly meeting,
and also at their meeting on first-day.
It was a contriting and bowing time with many, and we parted in the true unity,
fellowship, and heart-tendering love of the gospel of peace.
On second-day I was at Concord monthly meeting, which was a hard, laborious,
exercising season, both in time of worship and discipline;
things being much out of gospel order, by reason of strife and discord,
as opposite to the pure and peaceable government of the church of Christ,
as darkness is to light.
The evil spirit was kept down in a good degree,
and that which was out of order much helped by the power of Truth.

The 10th of the seventh month, 1759, I got to Philadelphia; the 18th,
several friends accompanying me, we went to Chester,
and the 19th on board a vessel which was bound for Barbados.
Some time after we were got to sea, I was closely exercised in my mind,
which brought me very low, in humble supplication before the Lord,
that he would be pleased to enable me to go through whatsoever he,
in the course of his infinite wisdom, might permit to come upon me,
whether for a trial of my faith, or any other of his wise and good ends.
I could appeal to him in great sincerity,
it was in obedience to his requirings that I had undertaken this voyage;
and not in my own will.
This was indeed with me as a time of renewing of
my covenant and coming under a close engagement,
that if he would be with me, to deliver and preserve me in the way that I had to go,
so that I might return again to his house in true peace, then he should be my God,
and I would serve him.
May I therefore, with all the Lord`'s servants everywhere,
not only make covenants when under close and deep exercise of soul;
but Oh! let us be concerned strictly to observe and keep them;
for I am a living witness for him, that he is a covenant keeping God with his people.

While I was under this living and fresh baptism,
those to whom I am the most nearly united in the closest ties of nature,
were brought nigh to me in spirit, though far separated in body,
with strong desires and fervent supplications, that they might be preserved in the truth,
and that the Lord in his infinite mercy,
would be pleased to visit their souls with a fresh visitation of his pure love.
The churches also of the Lord, especially those people I had so lately visited,
and had at times been so closely engaged for, in the love of the Father,
were spread before me in the nearest manner, with fervent prayer,
that they might abide in his love, stand in his counsel, and live in his holy fear;
that so we might still be a people to his praise,
and bring honour to his great and holy name,
and the profession we are making of the blessed Truth;
that the blessings which he has reserved, and laid up in store, might not be withheld,
but plentifully showered down upon his heritage.

My mind now was much eased,
and that which had been as a load upon my spirit was taken away,
and I was freely resigned to the will of God.
At that time, if I rightly knew my own heart, the fear of death was also removed,
and I trust, the occasion of it, which is sin;
for I did not find that my conscience condemned me, though I well know,
I have nothing to trust in but divine mercy,
through my dear Lord and Saviour Jesus Christ, in whom, and by whom,
all our sins are taken away, and we are redeemed unto God,
and that by his most precious blood.
It is by him also we have access to the Father,
his spirit bearing witness with our spirits, that we are his children, often crying,
Abba, Father, through the eternal spirit, which helps our infirmities,
and makes intercession for us; enabling us to ask aright,
and pray in an acceptable manner.

I may not omit remarking at this time, when the French were nigh taking us,
my spirit was so at liberty, and over them and all the powers of darkness in the Lord,
that I did not see it would be so;
and having had great freedom and liberty in my mind to go in this same vessel,
I could not reflect upon myself for missing it in any respect,
except it was in making mention of it sometimes too freely,
which it is likely some might lay hold of, and that not to their own advantage.
When we were taken, the Frenchmen, considering all their views were for plunder,
did not use me ill.
They took my little money, some of my linen, and part of my other wearing apparel;
but my bed and chest, with many other necessaries, they let me keep;
which was of great service to me afterwards.
I was now in a part of the world where I was a stranger, and no money of my own left;
yet I do not remember that I either murmured or repined at what had befallen me;
or that any distrustful thoughts rose in my heart,
so as to trouble and oppress my spirit;
which I esteemed as one of the many singular favours
I have received from the great and merciful hand.

The privateer belonging to Martinico, we landed at a town called St, Peter`'s;
a great part of which was laid in ashes about two weeks after we were set at liberty,
as I was afterwards informed.
We were all had to prison; but our captain, myself, the mate, and a passenger,
were put into a little room, which opened into the prison yard.
I think it was about twelve feet square, and we upwards of twenty, if I remember right,
to lie in it.
Before we left the place, my fellow prisoners behaved courteously and civilly,
none of them offering me any abuse,
though I had often to reprove and exhort them to amend their lives.

It was extremely hot weather, and our yard, where we had liberty to walk,
as well as our lodging room, was exposed to the sun most of the day.
They let me have my bed in the night next to the door and window,
for the benefit of the air, which was an advantage; but, alas!
I had a great disadvantage along with it,
for the wash and filth of the courtyard came through a hole in the wall,
very nigh the window where I lay,
so that often in the night I was nigh fainting with the smell,
which the heat of the weather made very nauseous.
The bread allowed us was pretty good,
but almost every kind of food was loathsome to my
stomach in this stinking unwholesome place.
There were salt beef and pork for those that could eat them;
but it being neither soaked nor half boiled,
I perceived there was but little of it eaten by any.
My chief living, while there, was bread and water, sometimes a little coffee,
but that was seldom, for we could not always get it boiled.
Oatmeal mixed in water was what I often drank, it serving also for food.
The water they let the prisoners have, I believe, is very unwholesome,
it being taken up below, where the negroes wash their clothes,
and also where the filth of the town is cast in.
Most of the prisoners, I perceived, were troubled with a diarrhoea,
and I had not been there above two or three days, before I was taken with it; which,
with the extreme heat and unwholesomeness of the place, brought me so low and weak,
that it was hard work for me to walk about a little in the prison yard; but I strove,
and was helped indeed beyond my own expectation;
for after we were set at liberty from the prison,
we were six days on board the vessel that set us upon the English island,
in which time I think I suffered more hardship than while I was in prison;
for being very weak, and the weather still hot, close and sultry,
I could not abide in the cabin among the people, but was forced to lie upon the deck,
where I could get air, though I was exposed to the night dews, and gusts of rain,
which we sometimes had; all which tended to increase my disorder.
The French captain gave me the liberty of the cabin,
and showed me kindness in other respects.
We were becalmed under the island of Gaudaloupe, and came to an anchor in a cove,
where we took in fresh water; but I went not on shore.
I was informed there was a great mortality among the English soldiers;
and many others who went about business, were taken off very suddenly at this place.

The 7th of the ninth month they landed us at the island called St. Christopher`'s,
where I found some kind, friendly people; though the generality were very gay, light,
and airy.
After I had been there a little time, my disorder abating, I began to gather strength,
so as to walk about;
and I found a few here who had some knowledge of friends and their principles,
by reason of their education.
One Joshua Lawson, a sailmaker by trade, a man of good report among his neighbours,
was willing I should have meetings at his house,
he having a large room very suitable for that purpose.
So I had several meetings, the town`'s people coming pretty generally,
and several were reached, I believe, by the heart-searching power of Truth,
which opened to them their states and conditions, especially some of the younger sort,
who were tender, and very desirous to have meetings.
But alas! their eye and expectation began to be so upon the poor, weak instrument,
that I queried in my own mind, whether I should have any more meetings with them;
for that spirit, which hungers after words,
sometimes shuts up the spring of the true ministry;
or it is withheld for a time on that account.

It now revived in my mind,
that I had felt a draught of the Father`'s love towards the island of Nevis,
when we sailed past it, in our passage from Martinico;
though I was told by one that knew the place,
such was the conduct of many of the inhabitants,
there were little hopes of getting a meeting, or being received there.
But this did not discourage me,
finding something in my mind which removed that obstacle out of the way.
Therefore I, with Caleb Copeland, a young man from North America, took boat,
and in a few hours arrived at Charlestown, the chief place on the island.
We took up our quarters at a tavern.
The day following being their general court, many of the inhabitants came to town,
and the place where we were being nigh the courthouse,
and the grand jury doing their business and dining there, drew a pretty deal of company.
Most of them, at their first seeing me,
seemed as though they could hardly be satisfied with gazing;
but I endeavoured to keep my eye to the Lord,
whose presence I felt to be near me in a good degree, to keep me still and quiet.
So they had their full view of me, till their curiosity was pretty well satisfied.
They offered no other incivility than fleering, Ishmael like.
The grand jury, either out of kindness, or further to satisfy their curiosity,
sent us an invitation to dine with them; but it being late before they went to dinner,
our landlady ordered ours sooner.
I did not find anything in my mind against eating with them,
though many of them are a light, vain, airy people,
and their company not desirable to a solid mind.

They sent a messenger for us when they sat down, by whom I sent word we had dined.
But they sent again, so I went in and told them we took their invitation kindly,
but we had dined, and therefore desired to be excused from sitting down with them.
They did not seem so light and airy now as they did before;
but said they should have been glad to have our company.
I observed they are very much in the custom of drinking healths,
as well as using many other vain compliments, which I had to show my dislike to,
not only by not using them,
but in letting them also know they were against our principles,
and the apostle`'s advice to the believers, where he says,
"`Be not conformed to this world; but be transformed, by the renewing of your minds.`"
I much desire my children may take notice of these little remarks,
and put in practice that excellent advice of the apostle,
not to be conformable to the world`'s language, vain customs and fashions,
which deface that beautiful image and likeness man was first created in.
For everything was good that God made, and had an excellency and beauty in it, and man,
the greatest of all, as long as he keeps his commandments;
but he loses that likeness and image of innocency,
by hearkening to the voice of the serpent,
who is called the prince of the power of the air,
that now bears rule in the hearts of the children of disobedience.
I would therefore, my dear children,
that you may come to know a being transformed by
the renewings of the grace and good spirit of Truth,
upon your minds and understandings, into the nature, image,
and innocency of the children of God, and stand in it, by keeping his commandments;
for herein is man`'s perfection.

A meeting had been proposed to be held in the courthouse, several seeming to forward it,
especially an old priest, who bestirred himself pretty much;
which I thought somewhat strange.
When it was nearly time for the meeting, he went along with me to the courthouse,
where the justices and several others had dined, and had not yet broken up;
but that was more than I knew before I went in.
However, the priest told them there was a gentleman, as he was pleased to call me,
wanted to give them a sermon,
and requested that they would give liberty of the hall for a meeting to be held;
but one whom they called their chief judge started up in a heat,
and said they had not done; and besides, they wanted no sermons; as for his part,
he never loved to hear one in his life.
A vulgar and unsavoury expression to come out of the mouth of one in his station;
and it made me that I could hardly tell what to say about having a meeting that night,
only as several of the people from various parts of the island were there,
it seemed a very suitable opportunity.
However, the old priest was not at all discouraged with the repulse he had met with;
he being resolved I should have a meeting, went over to the tavern where we lodged,
and got the liberty of a chamber, and then came and told me there was a convenient room,
and several already waiting.
I went, and found everything in good order for a meeting, except the people`'s minds;
I was also in great poverty, but I think quiet and much resigned.
I sat in silence a considerable space, in which time they were very restless,
and rude in their behaviour, such as I had seldom seen or heard before;
at length I had something rose in my mind to say, which reached, I believe,
the witness of truth in them; for they became very quiet and still,
and sat like another sort of people;
and many after meeting confessed to the truth of what had been spoken.

I had another meeting at that place, and many came.
It was a solemn, baptizing time.
The Lord`'s power had the dominion over all the rough and unruly spirits;
praises be to his all powerful name forever!
There stood up a man at the close of this meeting, and said,
he hoped what had been delivered would have a good effect;
for it was very suitable advice.
More he said, which is not needful to pen;
and I thought it was in a good degree of sincerity.
Then turning to me, he gave me a friendly invitation to his house.
I told him I took it kindly, and should come if opportunity would serve.
The company being pretty much gone, he entered into a little discourse with me,
and told me, he himself was also a fellow-labourer in the Lord;
but he had as little the look of a priest, as any I had ever seen, as I thought.
He told me also, he perceived that we had the advantage of them,
in that we did not tie ourselves up to one text of scripture, as they did,
and so could speak to the several states of the people; for he said,
it could not be supposed that one remedy could be suitable to every disease.
I made some remarks on his just observation, with something concerning the true ministry,
the operation of the spirit, and that it was not to be limited;
against which he made no objection, but freely assented to the Truth.
We parted in a kind and friendly manner.
I found he was a man of good understanding, bore a very good character among the people,
and was well beloved.

In the evening, after he was gone, there came a messenger from one Burnet,
a man of note in the island, to desire me to pay him a visit before I left the place;
which I did the next morning.
He received us very respectfully, without making much ceremony.
He asked me some questions concerning my travels and usage among the French,
which I gave him some account of.
He did not seem to want to enter into any discourse about religious matters,
but desired I would stay longer with them upon the island;
for he said there were several who were the descendants of Quakers,
and undoubtedly would be glad to see me.
But that did not at all induce me to stay, I finding myself pretty easy to leave them;
hoping the Lord in his own time will send his servants
and faithful labourers not only into this island,
but many others in this part of the world,
where the gospel rain has not been so plentifully bestowed.
O, England, and North America!
Though these people are too much in the churlish dog`'s nature,
yet many of them would be glad to partake of the crumbs that fall from your tables.
Your dainty full stomachs have often loathed the honey-comb,
and their poor souls are wandering about upon the barren mountains of a lifeless profession,
seeking the living among the dead.
May we therefore, that have received the knowledge of the Truth,
and been so often watered, be faithful, and bring forth fruits,
answerable to the blessings received!
Then will the Lord, I am fully persuaded,
send forth from among us such as shall bring them to Christ
the good Shepherd and the fold of true rest and peace.

But to return.
After I had stayed as long as time would permit, and was taking my leave of the man,
he put a parcel of money into my hand, which I returned,
and told him that we did not receive any money for preaching.
He said, we could not travel without expenses, and I had been taken by the French,
and had suffered some loss, and as he gave it me freely, I might receive it.
I told him, I was not then in necessity, therefore was not free to take it;
but acknowledged it was his good will, and so took my leave of him.
After I had been a little time at our inn,
we understood he had sent his servant to the landlady,
to charge her to take nothing of us, for he would pay all our expenses;
but it was already paid; and I saw it to be highly expedient for us,
to remove all cause from them that might take occasion,
that the ministry might not be justly blamed.
I left them in a loving good disposition of mind towards friends,
and am fully persuaded there are hungerings begotten
in the hearts of some of them after the true bread.

After I returned to the island called St. Christopher`'s, where I had taken lodgings,
not knowing how long I might stay, I was not easy to omit having meetings,
especially on first-days.
Several people coming out of the country, I had freedom to sit with them,
most of them behaving in a becoming and solid manner.
Truth sometimes favoured us in time of silence;
and though I had thought I should have been shut up,
I found the spring of the gospel was still opened towards the people at times,
in the free extendings of God`'s love.
And it came into my mind, in the opening of Truth,
that the Lord has a seed sown in those islands, which lies under the clods of the earth;
but its rising and coming into dominion must be left to his time;
he being able to dethrone antichrist, bring down his kingdom, with all his strong holds,
and in the room thereof, to establish his own everlasting righteousness;
that so in the very place where it was said, they are no people,
there shall they be called the children of the living God.

I found some of them desirous that I would visit them in their families,
which I complied with, as I found freedom;
often having to set before them their unchristian practice,
in keeping their fellow creatures in slavery for term of life,
and the cruelty they used towards them, which exceeded all that I had ever seen before;
and it raised such a just indignation in my heart,
that I used great freedom of speech sometimes in conversation.
Yet I trust I did not exceed the bounds of Truth,
for I perceived it always had some good tendency, either to silence,
or bring some acknowledgment from them, that the practice was unchristian,
and not to be justified; that they had no right to plead for keeping them,
but that of force, and they were a daily plague,
and caused them to run into a great deal of sin.
Thus I have heard some of them complain, wishing they had never had them,
or had some other way to get their bread.
So we may perceive the Lord is rising, by his pure witness,
in judgment in the hearts of those negro keepers, showing them the practice is evil,
and they cannot justify it, because the light condemns it,
and makes it manifest to them to be evil.
I tarried at this place longer than I expected;
but hope it was not time spent altogether unprofitably.
And although I have been hindered from going to the place I at first set out for,
I have evident tokens of God`'s love and fatherly care over me,
in the various steps I have had to tread.
Yet notwithstanding this evidence of divine approbation, I have not been insensible,
that mouths would be opened, not only against me, in saying I was wrongly led,
or under a deception, but also against the Truth; for the Truth has many enemies,
and none greater and readier to judge others,
than those that are making a profession of it, but dwell not in the life and power.
But it is not a new thing to be counted deceivers, and yet be true.

While I tarried here, I often enquired for a passage to the windward islands,
that such occasion might be taken away, and I be clear of the blood of all men.
I thought by way of Antigua might be proper; but when I made some attempts towards it,
I was always stopped in my mind, not being free to leave the place where I was.
But when I had tarried some time longer,
and had many good opportunities among the people,
I felt myself quite easy to leave the island; and not only so,
but likewise a strong desire to be gone; also that view, and those drawings I had before,
to visit the other islands, were entirely removed,
and I was easy to return in a vessel which was then bound for Philadelphia.
Therefore, taking leave of those I was pretty nearly acquainted with in Basseterre,
the chief town on the island, I went by land to Sandy Point,
where the vessel lay to take in part of her cargo.
Here I had a meeting with the town`'s people the day before we set sail,
which was the 2nd of the eleventh month 1759, having been upon this island, and Nevis,
eight weeks.

While I tarried in those islands, there was a great mortality among the people,
but it did not bring that awfulness and humility upon their minds,
which it ought to have done;
and therefore the divine hand undoubtedly will be stretched out still.
The captain and men behaved very civilly to me in this passage.
I had several meetings with the ship`'s company, which had some good effect, I believe,
upon the seamen.
We arrived at Philadelphia the 29th of the eleventh month,
where I was very kindly received by my friends, who had, I believe,
nearly sympathised with me in my late exercises.
I stayed in the city a little more than two weeks, except a short visit to Wilmington.
A conference was held with the Indians while I tarried here, which I was at;
and Daniel Stanton and myself, with a few other friends,
had a meeting with them at Philadelphia in the state house.

After some time of waiting in silence, I had something to say, and one Isaac Still,
an Indian, who could speak English,
delivered the substance of what I said in the Indian language.
He appeared tender and well satisfied, being a sensible, sober young man.
Tedeuscung, and several of the Delaware chiefs were present,
and a few of the Jersey Indians.
They were solid, attentive, and behaved in a becoming manner.
The meeting ended in humble prayer and supplication to Almighty God.
My stay being but short here, after I returned from the West Indies,
I endeavoured to take my leave of friends in as general a manner as time would permit,
and the 16th of the twelfth month 1759, being the first of the week,
after a good and satisfactory season with friends at Pine street meetinghouse,
I took my farewell of them in the uniting love and
pure fellowship of the gospel of peace.

I went on board the ship __Carolina,__ at the wharf; the master`'s name was James Friend,
a kind, courteous man.
We had a very difficult passage, by reason of high winds, and a leaky vessel; yet,
through the mercy and goodness of kind Providence,
we arrived safely at London the 29th of the first month 1760,
where I stayed but a few days before I took leave of friends there,
and returned home to my dear wife and children, who, in my absence, with all that I had,
had been kept, blessed, and preserved, far beyond my own expectation,
or indeed my deserving as a creature.
I desire I ever may be thankful for such unspeakable favours and mercies,
and give him the praise, who is worthy forever!
